In [1]:
import pygame
import sys
import numpy as np
import random
import pandas as pd
import time
import tensorflow as tf
from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession

config = ConfigProto()
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)
BATCH_SIZE=32


pygame 2.1.2 (SDL 2.0.18, Python 3.7.6)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
width=10
height=10
pixel_size=(50,50)
display_size=(pixel_size[0]*width,pixel_size[1]*height)
record=[]
game_num=1
p=0
step=0

color_dict={
    "wall":(177,177,177),
    "target":(0,177,0),
    "normal":(255,255,255),
    "start":(177,0,0)
}

map_dict={
    "target":(7,2),
    "start":(2,height-1),
    "tank1":(7,4),
    "tank2":(5,2),
    "tank3":(random.randint(3,width-3),random.randint(2,height-3)),

   }

wall_location=[]
for w in range(width):
    wall_location.append((w,0))
    wall_location.append((w,height-1))
    
for h in range(height):    
    wall_location.append((0,h))
    wall_location.append((width-1,h))
    
wall_location.remove(map_dict.get("start"))
wall_location.append((map_dict.get("start")[0],map_dict.get("start")[1]+1))
map_dict['wall']=wall_location

df100=pd.DataFrame(columns=['s','a','s_','r'])
df1=pd.DataFrame(columns=['s','a','s_','r'])
df0=pd.DataFrame(columns=['s','a','s_','r'])

epsilon=0
reward=[-0.02]
gamma=0.9
a_dict={
    0:'up',
    1:'down',
    2:'left',
    3:'right'
}

s_index={}
for i in range(width-2):
    for j in range(height-2):
        s_index.update({(i+1,j+1):(i+(j*(width-2)))})

s_index.update({map_dict.get("start"):(width-2)*(height-2)})   


In [3]:
def draw_map():
    for i in range(width*height):
        w=i-width*(i//width)
        h=i//width
        
        if (w,h)==map_dict.get("target"):
            color=color_dict.get("target")
        elif (w,h)==map_dict.get("start"):
            color=color_dict.get("start")
        elif (w,h) in map_dict.get("wall"):
            color=color_dict.get("wall")
        else:
            color=color_dict.get("normal")
        
        pygame.draw.rect(game_map,color,(w*50,h*50,pixel_size[0],pixel_size[1]))

        
class tank(pygame.sprite.Sprite):
    def __init__(self,filename,location):
        pygame.sprite.Sprite.__init__(self)
        self.image = pygame.image.load(filename).convert()
        self.image = pygame.transform.scale(self.image,(50,50))

        self.rect = self.image.get_rect()
        self.rect.topleft=(location[0]*pixel_size[0],location[1]*pixel_size[1])

        
def crash_wall():
    if (person_site[0],person_site[1]) in map_dict.get("wall"):
        return True
    else:
        return False
    
    
def crash_detect(sprite1,sprite2):
    global game_num
    global game_state
    result=pygame.sprite.collide_mask(sprite1,sprite2)
    
    if result:
        if sprite2 in tank1_group:
            print("这是第{}局游戏，我死了".format(game_num))
            if game_num>20:
                print('最后20盘的胜率为{}'.format(record[-20:].count(1)/20))
            record.append(0)
            reward.append(-1)

        elif sprite2 in princess_group:
            print("这是第{}局游戏，我赢了".format(game_num))
            if game_num>20:
                print('最后20盘的胜率为{}'.format(record[-20:].count(1)/20))
            record.append(1)
            reward.append(1)

        game_num+=1
        game_state=1
        
        
def move(direction):
    global person_site
    global step
    if direction=='up':
        person_site[1]-=1
        a= crash_wall()
        if a==True:
            person_site[1]+=1
        
    if direction=='down':
        person_site[1]+=1
        a= crash_wall()
        if a==True:
            person_site[1]-=1
    if direction=='left':
        person_site[0]-=1
        a= crash_wall()
        if a==True:
            person_site[0]+=1
    if direction=='right':
        person_site[0]+=1
        a= crash_wall()
        if a==True:
            person_site[0]-=1
        
    person.rect=(person_site[0]*pixel_size[0],person_site[1]*pixel_size[1],50,50)
    crash_detect(person,tank1)       
    crash_detect(person,tank2)   
    crash_detect(person,tank3)       

    crash_detect(person,princess)         
    step+=1

In [8]:
def pick_a(state):    
    if random.random()>epsilon:
        action=random.randint(0,3)
    else:
        x=model1.predict([state])
        action= x.argmax()
    return action


def one_turn():
    s1=int(person_site[0])
    s2=int(person_site[1])
    a=pick_a([s1,s2])
    move(a_dict.get(a)) 
    s1_=int(person_site[0])
    s2_=int(person_site[1])
    r=reward[-1]
    trace_collect(s1,s2,a,s1_,s2_,r)
    
    if game_num>50 and step%200==0:
        fit(10)
        
    if game_state==1:           
        reset()

        
def trace_collect(s1,s2,a,s1_,s2_,r):   
    global df100
    global df1
    global df0
    new_trace={
        's1':s1,
        's2':s2,
        'a':a,
        's1_':s1_,
        's2_':s2_,
        'r':r
    }
    if r==1:
        df100=df100.append(new_trace,ignore_index=True)
        df100=df100.iloc[-100:]
        #df100.to_csv('trace100.csv')
    if r==-1:
        df1=df1.append(new_trace,ignore_index=True)
        df1=df1.iloc[-1000:]
        #df1.to_csv('trace1.csv')
    else:
        df0=df0.append(new_trace,ignore_index=True)
        df0=df0.iloc[-4000:]
        #df0.to_csv('trace0.csv')
    
def preprocessing(batch_size):
    #df100=pd.read_csv('trace100.csv')
    #df1=pd.read_csv('trace1.csv')
    #df0=pd.read_csv('trace0.csv')
    ds100=df100.sample(batch_size,replace = True)
    ds1=df1.sample(batch_size//2,replace = True)
    ds0=df0.sample(batch_size//2,replace = True)
    train_ds=pd.concat((ds100,ds1,ds0))
    train_ds=train_ds.sample(batch_size)
    return train_ds
    
    

In [9]:
def train_step(train_ds):
    global p
    s = np.int32(np.stack((train_ds['s1'],train_ds['s2']),1))
    a = np.array(train_ds['a'])
    s_ = np.int32(np.stack((train_ds['s1_'],train_ds['s2_']),1))
    r = np.array(train_ds['r'])

    
    c1=np.zeros((len(train_ds),4))   #A方向外全为0的矩阵
    for i in range(len(a)):
        c1[i][int(a[i])]=1
    
    c2=np.ones((len(train_ds),4))    #A方向外全为1的矩阵
    for i in range(len(a)):
        c2[i][int(a[i])]=0
        
    d=np.ones((len(r)))
    for i in range(len(r)):
        if r[i]==1:
            d[i]=0
        elif r[i]==-1:
            d[i]=0
        else:
            pass
    
    qloss=model1(s) #取qt以外的值
    qt=model2(s_)   #取max的值
    qtarget=tf.reduce_max(qt,axis=1)*gamma*d+r
    qtloss=tf.transpose([qtarget,qtarget,qtarget,qtarget])*c1+qloss*c2
    

   
    with tf.GradientTape(persistent=True) as tape:
        #loss函数
        q=model1(s)                     
        loss=tf.reduce_sum(tf.square(qtloss-q))
        p=float(loss)
    
    gradient=tape.gradient(loss,model1.trainable_variables)
    opt.apply_gradients(zip(gradient,model1.trainable_variables))
    del tape

    

In [10]:
model1=tf.keras.Sequential([
    tf.keras.layers.Dense(4096,input_shape=(BATCH_SIZE,2),activation='relu'),
    tf.keras.layers.Dense(4096,activation='relu'),
    tf.keras.layers.Dense(1024,activation='relu'),
    tf.keras.layers.Dense(4)       #a,qmax=r+gamma*q_max
   ]
)

model2=tf.keras.Sequential([
    tf.keras.layers.Dense(4096,input_shape=(BATCH_SIZE,2),activation='relu'),
    tf.keras.layers.Dense(4096,activation='relu'),
    tf.keras.layers.Dense(1024,activation='relu'),
    tf.keras.layers.Dense(4)       #a,qmax=r+gamma*q_max
   ]
)

opt=tf.keras.optimizers.Adam(learning_rate=0.001)

In [12]:
def fit(epochs):
    for epoch in range(epochs):
        train_ds=preprocessing(BATCH_SIZE)
        for i in range(50):
            train_step(train_ds)
        print(str(p)+'.',end='')
        
        if (epoch+1)%10==0:
            print("EPOCH:",epoch+1)

    
def load_weight():
    model1.save_weights('DQN.h5')
    model2.load_weights('DQN.h5')
    
    
def debug():
    for i in range(width-2):
        for j in range(height-2):
            result=model1.predict([[i+1,j+1]])
            print(i+1,j+1)
            print(result)
            
            
def reset():
    global person_site
    global game_state
    person_site=[map_dict.get("start")[0],map_dict.get("start")[1]]
    person.rect=(person_site[0]*pixel_size[0],person_site[1]*pixel_size[1],50,50)
    game_state=0
    reward.append(-0.02)
    
    if game_num>70 and game_num%20==0:    
        load_weight()
        debug()

In [14]:
pygame.init()
clock = pygame.time.Clock()
pygame.display.set_caption("AI训练游戏")

screen = pygame.display.set_mode(display_size)
game_map=pygame.surface.Surface(display_size)
draw_map()

tank1_group = pygame.sprite.Group()
tank2_group = pygame.sprite.Group()
princess_group = pygame.sprite.Group()
person_group=pygame.sprite.Group()

tank1 = tank("img/tank.jpg",map_dict.get("tank1"))
tank2 = tank("img/tank.jpg",map_dict.get("tank2"))
tank3 = tank("img/tank.jpg",map_dict.get("tank3"))

tank1_group.add(tank1)
tank1_group.add(tank2)
tank1_group.add(tank3)


princess=tank('img/sidalin.jpeg',map_dict.get("target"))
princess_group.add(princess)

person_site=[map_dict.get("start")[0],map_dict.get("start")[1]]
person=tank('img/maintank.jpeg',person_site)
person_group.add(person)

reset()

while True:
    clock.tick(60)

    screen.blit(game_map,(0,0))
    tank1_group.draw(screen)
    princess_group.draw(screen)
    screen.blit(person.image,person.rect)
    tank2_group.draw(screen)
    
    
    one_turn()



    if game_num==50:
        epsilon=0.2
    elif game_num==100:
        epsilon=0.3   
    elif game_num==150:
        epsilon=0.4
    elif game_num==200:
        epsilon=0.5
    elif game_num==250:
        epsilon=0.6
    elif game_num==300:
        epsilon=0.7
    elif game_num==350:
        epsilon=0.8
    elif game_num==400:
        epsilon=0.9
        
    for event in pygame.event.get():
        if event.type ==pygame.QUIT:
            pygame.quit()
            sys.exit()
            

        
#       if event.type ==pygame.KEYDOWN:
#           if event.key == pygame.K_UP:
#               move('up')
#           if event.key == pygame.K_DOWN:
#               move('down')
#           if event.key == pygame.K_LEFT:
#               move('left')
#           if event.key == pygame.K_RIGHT:
#               move('right')
#           if event.key == pygame.K_SPACE:
                
                
     
    pygame.display.update()

这是第1局游戏，我死了
这是第2局游戏，我死了
这是第3局游戏，我死了
这是第4局游戏，我死了
这是第5局游戏，我死了
这是第6局游戏，我死了
这是第7局游戏，我死了
这是第8局游戏，我死了
这是第9局游戏，我死了
这是第10局游戏，我死了
这是第11局游戏，我死了
这是第12局游戏，我死了
这是第13局游戏，我死了
这是第14局游戏，我赢了
这是第15局游戏，我死了
这是第16局游戏，我死了
这是第17局游戏，我赢了
这是第18局游戏，我死了
这是第19局游戏，我死了
这是第20局游戏，我死了
这是第21局游戏，我死了
最后20盘的胜率为0.1
这是第22局游戏，我死了
最后20盘的胜率为0.1
这是第23局游戏，我死了
最后20盘的胜率为0.1
这是第24局游戏，我死了
最后20盘的胜率为0.1
这是第25局游戏，我死了
最后20盘的胜率为0.1
这是第26局游戏，我死了
最后20盘的胜率为0.1
这是第27局游戏，我死了
最后20盘的胜率为0.1
这是第28局游戏，我死了
最后20盘的胜率为0.1
这是第29局游戏，我死了
最后20盘的胜率为0.1
这是第30局游戏，我死了
最后20盘的胜率为0.1
这是第31局游戏，我死了
最后20盘的胜率为0.1
这是第32局游戏，我死了
最后20盘的胜率为0.1
这是第33局游戏，我死了
最后20盘的胜率为0.1
这是第34局游戏，我死了
最后20盘的胜率为0.1
这是第35局游戏，我死了
最后20盘的胜率为0.05
这是第36局游戏，我死了
最后20盘的胜率为0.05
这是第37局游戏，我死了
最后20盘的胜率为0.05
这是第38局游戏，我死了
最后20盘的胜率为0.0
这是第39局游戏，我死了
最后20盘的胜率为0.0
这是第40局游戏，我死了
最后20盘的胜率为0.0
这是第41局游戏，我死了
最后20盘的胜率为0.0
这是第42局游戏，我死了
最后20盘的胜率为0.0
这是第43局游戏，我死了
最后20盘的胜率为0.0
这是第44局游戏，我死了
最后20盘的胜率为0.0
这是第45局游戏，我死了
最后20盘的胜率为0.0
这是第46局游戏，我死了
最后20盘的胜率为0.0
这是第47局游戏，我死了
最后20盘的胜率为0.0
这是第48局游戏，我死了
最后20盘的胜率为0.0
这是第49局游戏，我死了
最后20盘

5 8
[[0.32405287 0.3571371  0.29397187 0.29952222]]
6 1
[[ 0.4718917  -1.4875715   1.1515639   0.84601486]]
6 2
[[ 0.87651867 -0.69678533 -0.48647907  1.0009836 ]]
6 3
[[ 0.27708027 -0.50972724 -0.6394199   0.1386062 ]]
6 4
[[-1.208268  -0.8926442 -0.6771288 -0.8274734]]
6 5
[[-1.1252874  -0.73555946 -0.9835806  -0.5337806 ]]
6 6
[[-0.18379048  0.05588286 -0.06456562  0.07152796]]
6 7
[[0.21912515 0.32198057 0.32082528 0.28628707]]
6 8
[[0.3073733  0.3750963  0.42002383 0.30857188]]
7 1
[[ 0.5045506 -1.9785109  1.7032042  1.0261805]]
7 2
[[ 0.8873381  -1.1479087   0.18623315  1.2118933 ]]
7 3
[[ 0.9996421  -0.58821493 -0.91927975  1.0635473 ]]
7 4
[[ 0.01027374 -0.41032082 -0.46435645 -0.05656845]]
7 5
[[-1.000271   -0.44767153 -0.61849296 -0.4491229 ]]
7 6
[[0.16844288 0.19153321 0.1385007  0.34713763]]
7 7
[[0.3900505  0.33506003 0.38429475 0.3969636 ]]
7 8
[[0.5080657  0.3964546  0.5089183  0.45938563]]
8 1
[[ 0.58718026 -2.4819782   2.2151124   1.2503586 ]]
8 2
[[ 0.7945685 -1.6756

7 2
[[ 1.0432959 -1.2379172  0.6333072  1.4502202]]
7 3
[[ 0.99869794 -0.84911203 -0.17152327  0.9458713 ]]
7 4
[[-0.16324604 -0.39347565 -0.13223132 -0.12186924]]
7 5
[[-1.0572915  -0.00863021 -0.03251209 -0.7260498 ]]
7 6
[[-0.3650345   0.12769441 -0.23818749 -0.19048774]]
7 7
[[0.23003976 0.3910228  0.19869362 0.36312243]]
7 8
[[0.269034   0.46991757 0.38057864 0.4966775 ]]
8 1
[[ 1.3297906 -2.0214152  1.5384353  2.4527051]]
8 2
[[ 1.2593718  -1.5834472   0.99976885  1.925817  ]]
8 3
[[ 1.234987   -1.1705072   0.18478787  1.4008555 ]]
8 4
[[ 0.8072118  -0.7427844  -0.19272295  0.79244107]]
8 5
[[-0.4742344  -0.13771823  0.10125817 -0.0662591 ]]
8 6
[[-0.3289953   0.31418592  0.28669232  0.11757783]]
8 7
[[0.19407138 0.42477047 0.3186697  0.40107092]]
8 8
[[0.3049212  0.52803934 0.40242046 0.56064826]]
这是第100局游戏，我死了
最后20盘的胜率为0.0
这是第101局游戏，我死了
最后20盘的胜率为0.0
3.564738653949462e-05.0.00028807666967622936.0.0012098749866709113.0.0002354854514123872.3.5729339288081974e-05.0.0004137563810218

0.00024464158923365176.0.0008821288356557488.0.008604444563388824.0.0006924283225089312.0.0004985264968127012.0.0010910441633313894.0.00022586988052353263.0.0016986941918730736.0.0008767362451180816.0.00025267808814533055.EPOCH: 10
这是第117局游戏，我死了
最后20盘的胜率为0.15
3.63640756404493e-05.0.001468862290494144.0.0017159453127533197.0.0005162634188309312.0.00033087562769651413.0.0005534752272069454.0.0002726476523093879.3.898413706338033e-05.0.0004051618161611259.0.0007720603025518358.EPOCH: 10
0.011565589345991611.0.0006892010569572449.0.0009000037098303437.0.0028855339623987675.0.0014339950866997242.0.0003683138347696513.0.0023130530025810003.0.0007361542666330934.0.005030449479818344.0.00434779142960906.EPOCH: 10
这是第118局游戏，我死了
最后20盘的胜率为0.15
这是第119局游戏，我死了
最后20盘的胜率为0.15
1 1
[[0.09434748 0.195568   0.16330273 0.15434852]]
1 2
[[0.04650113 0.20509523 0.19870782 0.09157787]]
1 3
[[0.04182306 0.223283   0.24617995 0.06509282]]
1 4
[[0.05602941 0.23040712 0.2830261  0.04159036]]
1 5
[[0.09288452 0.20

0.0010726326145231724.0.0012015084503218532.0.0002236224536318332.0.0005900414544157684.7.753349927952513e-05.2.2767357222619466e-05.0.004341450519859791.0.000290597730781883.0.00034341742866672575.2.1268369891913608e-05.EPOCH: 10
这是第154局游戏，我死了
最后20盘的胜率为0.15
0.0001672750513534993.0.0008436198113486171.6.255646439967677e-05.0.0002647065557539463.0.0007177068619057536.0.00034271314507350326.0.0004698332049883902.0.0014422982931137085.0.0005437115905806422.1.5502662790822797e-05.EPOCH: 10
9.719482477521524e-05.0.000146682039485313.0.00011046582949347794.0.00025568457203917205.0.00028611739980988204.4.605500362231396e-05.0.00014652042591478676.0.0002857492072507739.0.0005229452508501709.0.0005950030172243714.EPOCH: 10
这是第155局游戏，我死了
最后20盘的胜率为0.15
这是第156局游戏，我赢了
最后20盘的胜率为0.15
0.00023626464826520532.0.0008509205072186887.0.00015289784641936421.0.00031764397863298655.7.159856613725424e-05.0.0008490970940329134.0.00015517201973125339.2.0794832380488515e-05.0.00040330091724172235.6.49740977678448

2.6363608412793837e-05.2.2463882487500086e-05.0.00010611535981297493.6.52791204629466e-05.7.382127660093829e-05.2.733196561166551e-05.0.0002655845892149955.1.7897331417771056e-05.0.00020770479750353843.6.215281609911472e-05.EPOCH: 10
6.600590131711215e-05.0.00015275529585778713.8.701146725798026e-05.5.562722071772441e-05.2.656604010553565e-05.0.0016663657734170556.0.00029677714337594807.0.0002988747146446258.0.00011097585957031697.8.73916142154485e-05.EPOCH: 10
0.00029076269129291177.9.367960956296884e-06.0.00010276149987475947.0.0020964988507330418.0.004682046361267567.0.0004188315651845187.2.6025161787401885e-05.0.0003535834839567542.0.0025536378379911184.0.00011208903742954135.EPOCH: 10
0.0004614129429683089.0.00029764504870399833.0.00019818500732071698.4.9450005462858826e-05.0.00010241763084195554.0.00024495014804415405.0.0004460520576685667.5.817171040689573e-05.0.002560525666922331.0.0015836120583117008.EPOCH: 10
0.00010551504965405911.0.00036107044434174895.7.97705797594972e-05.

7 2
[[1.0082854  0.27109855 0.39633983 1.1570951 ]]
7 3
[[ 0.9999807 -0.8730775 -1.0882658  1.0123409]]
7 4
[[ 0.14180978 -0.23175658 -0.785615    0.29390812]]
7 5
[[-1.0004635   0.27244663  0.06182028  0.17492214]]
7 6
[[0.19694021 0.26062325 0.22612906 0.25610253]]
7 7
[[0.25404027 0.27597213 0.24815539 0.27621132]]
7 8
[[0.28401405 0.30348307 0.28274894 0.3020689 ]]
8 1
[[1.6047561 1.3548332 1.1930496 1.499763 ]]
8 2
[[1.3127061 1.0392615 1.0000173 1.3095758]]
8 3
[[1.0667523  0.27339372 0.07906725 1.1061934 ]]
8 4
[[ 0.99549186  0.08148319 -0.999689    0.68769056]]
8 5
[[0.17776868 0.25318035 0.2000524  0.26798362]]
8 6
[[0.21299873 0.26801708 0.23526044 0.26435867]]
8 7
[[0.26703328 0.28488785 0.25865138 0.28541827]]
8 8
[[0.29513535 0.31444454 0.29599178 0.31244648]]
0.00024996939464472234.0.00019065120432060212.0.0005295223090797663.9.784906433196738e-05.0.0001708686031633988.0.00011724524665623903.0.00021446459868457168.0.0003117327578365803.0.00027891353238373995.4.72609681310

7 4
[[-0.5244082  -0.60425305 -0.7192669   0.11700924]]
7 5
[[-0.9921782   0.16076571  0.23856199  0.08964554]]
7 6
[[0.1738944  0.22033572 0.18999694 0.23565724]]
7 7
[[0.20696749 0.23806429 0.21431826 0.2511696 ]]
7 8
[[0.22377466 0.2569108  0.23507643 0.2706973 ]]
8 1
[[1.2705069 1.2284735 1.1976718 1.5797561]]
8 2
[[1.0494746 1.0253305 1.002892  1.3540236]]
8 3
[[0.853754   0.6035511  0.52001446 1.1507773 ]]
8 4
[[ 0.8612976  -0.06981391 -1.033858    0.78491557]]
8 5
[[-0.14139529  0.21174373  0.2086412   0.18359953]]
8 6
[[0.20220648 0.2322216  0.2079475  0.24574526]]
8 7
[[0.21907322 0.25112247 0.22876713 0.26534486]]
8 8
[[0.2357928  0.26986766 0.24941409 0.28477144]]
0.0009741645189933479.9.519200102658942e-05.0.0009588019456714392.0.00039316710899583995.0.00034735543886199594.0.00078119634417817.0.0017950418405234814.0.0002311038988409564.0.0006552192498929799.0.01186633761972189.EPOCH: 10
这是第220局游戏，我赢了
最后20盘的胜率为0.35
0.0015100413002073765.0.0002766495745163411.0.00019356539996

2 5
[[ 0.05472427 -0.08023688  0.06105651 -1.0889984 ]]
2 6
[[0.13467267 0.14573383 0.12469354 0.12629676]]
2 7
[[0.1386472  0.14145055 0.12869257 0.16347972]]
2 8
[[0.13530143 0.14599383 0.12502962 0.16848382]]
3 1
[[0.13753793 0.12146682 0.10482747 0.07450917]]
3 2
[[0.11920038 0.10689738 0.12978867 0.05740142]]
3 3
[[-0.07122952  0.04228713  0.15290134 -0.4253066 ]]
3 4
[[-0.49823368 -0.65698314 -0.08983892 -1.0281558 ]]
3 5
[[-0.7824115  -0.87457716 -0.39096713 -1.0006305 ]]
3 6
[[-0.82750654  0.17629112  0.050779    0.0646655 ]]
3 7
[[0.13191727 0.165109   0.14721568 0.18271373]]
3 8
[[0.16148254 0.17701626 0.1650527  0.18689716]]
4 1
[[ 0.09019921 -0.45054325 -0.26313084  0.01453453]]
4 2
[[-0.63132066 -0.70589495 -0.47046107 -0.99886525]]
4 3
[[-1.0744349  -1.0077189  -0.65860987 -0.9717208 ]]
4 4
[[-0.974017   -0.9702383  -0.77337027 -0.9786751 ]]
4 5
[[-0.9701083  -0.97246885 -0.8752498  -0.9912982 ]]
4 6
[[-0.97078466  0.18081287 -0.03054775  0.13898414]]
4 7
[[0.08501565 0.1

1 8
[[0.12717342 0.13518625 0.13372344 0.13510045]]
2 1
[[0.07986978 0.06738223 0.11262491 0.02206235]]
2 2
[[0.08778283 0.07531832 0.11354878 0.04619196]]
2 3
[[ 0.07486774  0.06296231  0.10147801 -0.00098787]]
2 4
[[ 0.05644038  0.05282437  0.10366199 -0.08803092]]
2 5
[[ 0.04320419  0.02443625  0.10665722 -0.23646697]]
2 6
[[ 0.07562584  0.07455784  0.10962607 -0.04466902]]
2 7
[[0.1275067  0.13456509 0.13397914 0.13556993]]
2 8
[[0.1275067  0.13456509 0.13397914 0.13556993]]
3 1
[[ 0.05524562  0.03107119  0.10064056 -0.10487872]]
3 2
[[ 0.05534147  0.02767773  0.1073518  -0.12207735]]
3 3
[[ 0.02109112 -0.01304564  0.10073181 -0.25920513]]
3 4
[[-0.19986814 -0.1425738   0.10907569 -0.7378531 ]]
3 5
[[-0.25428838 -0.20248187  0.05934054 -0.99978197]]
3 6
[[ 0.05559368  0.13927202  0.05569641 -0.2631027 ]]
3 7
[[0.1346888  0.14277798 0.14025986 0.14389789]]
3 8
[[0.1275067  0.13456509 0.13397914 0.13556993]]
4 1
[[ 0.13832755 -0.43309924 -0.0257089  -0.11514661]]
4 2
[[-0.21211526 -0

0.0003710296587087214.9.475128899794072e-05.0.0007797633879818022.0.0007819560705684125.0.0024880659766495228.0.00011230660311412066.0.0016740928404033184.0.0014042770490050316.0.00015399305266328156.0.0002879587118513882.EPOCH: 10
0.001401082263328135.0.0008533127838745713.0.0001288899511564523.0.00023434869945049286.5.6730561482254416e-05.4.116233321838081e-05.0.00011658012226689607.0.0018896651454269886.0.00040647637797519565.6.423668673960492e-05.EPOCH: 10
0.004005457740277052.0.00961900781840086.0.0002835073973983526.0.00016689584299456328.0.0006296581705100834.0.0009635260212235153.0.00017156964167952538.9.757783845998347e-05.0.00014607507910113782.0.0004139101947657764.EPOCH: 10
4.135629569645971e-05.6.862498412374407e-05.0.001015482353977859.0.00011733506835298613.0.00018481735605746508.0.00018726536654867232.5.175267142476514e-05.2.2326199541566893e-05.0.0010043783113360405.0.00017039089289028198.EPOCH: 10
这是第292局游戏，我死了
最后20盘的胜率为0.55
这是第293局游戏，我赢了
最后20盘的胜率为0.5
这是第294局游戏，我死了
最后

1 7
[[0.05610169 0.04432091 0.05700657 0.13417797]]
1 8
[[0.0354905  0.04915655 0.06622997 0.11998337]]
2 1
[[-0.00933063  0.03467252  0.05751761  0.46579635]]
2 2
[[-0.01341259  0.03448055  0.05797517  0.48027694]]
2 3
[[0.01743764 0.03593141 0.05451711 0.3708371 ]]
2 4
[[0.02137007 0.04293039 0.0566432  0.32266927]]
2 5
[[0.04047719 0.03701494 0.05193456 0.2891053 ]]
2 6
[[0.07185319 0.03858138 0.04850966 0.17642319]]
2 7
[[0.05851799 0.04375017 0.05587962 0.1358726 ]]
2 8
[[0.03767711 0.048544   0.06406863 0.12228119]]
3 1
[[-0.01129311  0.03458022  0.05773759  0.47275817]]
3 2
[[-0.00375718  0.03493463  0.05689288  0.44602478]]
3 3
[[0.03179291 0.03917985 0.05373477 0.3056041 ]]
3 4
[[ 0.3390335   0.19674087 -0.08067949 -0.6354612 ]]
3 5
[[-0.2535953  -0.18347049 -0.39079756 -0.936108  ]]
3 6
[[0.12696618 0.07403375 0.10580973 0.18188989]]
3 7
[[0.07482727 0.07399149 0.13475353 0.15246786]]
3 8
[[0.02294683 0.07407902 0.1638915  0.12321659]]
4 1
[[ 0.62966675 -0.2208643  -0.1818799

4 1
[[ 0.8163661 -0.3100322  0.3257164  1.2392248]]
4 2
[[-0.27189165 -0.5270337   0.22878432 -0.9674727 ]]
4 3
[[-0.7615179  -1.0165476   0.14665987 -0.9835377 ]]
4 4
[[-0.7758569  -1.0024362   0.13091984 -0.99065995]]
4 5
[[-1.0205336 -1.2656703 -1.1115454 -1.0072405]]
4 6
[[-0.99983674  0.19043043 -0.40858018  0.16789019]]
4 7
[[0.033785   0.25178352 0.28934053 0.23743188]]
4 8
[[0.28085393 0.2832018  0.267856   0.289303  ]]
5 1
[[ 0.91381556 -1.004546   -0.3010782   1.6482201 ]]
5 2
[[ 0.28136265 -1.0758009  -1.0491034   0.501546  ]]
5 3
[[-0.98931557 -0.9926795  -0.31640232 -1.0043213 ]]
5 4
[[-0.99231    -0.9980657  -0.35162076 -1.0045601 ]]
5 5
[[-0.9696111  -0.65492463 -1.0435518  -0.81398034]]
5 6
[[-0.8499967   0.2852374   0.1731632   0.28949365]]
5 7
[[0.27280992 0.25726777 0.26363128 0.2700768 ]]
5 8
[[0.29654115 0.29436255 0.28244406 0.3023177 ]]
6 1
[[1.102747   0.42951363 1.1750606  1.6305745 ]]
6 2
[[ 0.91415524 -0.8820883  -0.7112284   1.0010846 ]]
6 3
[[-0.79568356 -1

5 8
[[0.23764159 0.25585356 0.24201176 0.26207364]]
6 1
[[1.1776377 0.6542001 1.0991076 1.3541577]]
6 2
[[ 0.9360275  -0.9240183  -1.0123109   0.99908435]]
6 3
[[-0.6093545  -1.150493   -1.1993982  -0.35175818]]
6 4
[[-1.0555055  -1.0708724  -0.99832374 -1.0313078 ]]
6 5
[[-1.0055704  -0.25527743 -0.9115563  -0.6514162 ]]
6 6
[[-0.65468085  0.23395759  0.2185503   0.24902187]]
6 7
[[0.23986022 0.23618457 0.24150866 0.24887516]]
6 8
[[0.23675753 0.26754755 0.242744   0.2700946 ]]
7 1
[[1.3312186 0.99912   1.3461531 1.4744141]]
7 2
[[1.3101492 0.5721535 0.6735502 1.1124895]]
7 3
[[ 0.99944454 -0.9894648  -1.0807911   0.6454301 ]]
7 4
[[-0.443236   -1.1362916  -1.07502    -0.67200726]]
7 5
[[-1.0002623   0.08885241 -0.5372973   0.09245893]]
7 6
[[-0.12629472  0.23311898  0.254398    0.22423075]]
7 7
[[0.23908645 0.2478995  0.24235359 0.2569552 ]]
7 8
[[0.23600529 0.27923095 0.24360603 0.2781607 ]]
8 1
[[1.4994754 1.4694788 1.3672777 1.4911683]]
8 2
[[1.4912087 1.2131568 0.9990675 1.353658

6 3
[[-0.6963804 -1.0902306 -1.1165309 -0.6143311]]
6 4
[[-0.9986421 -1.0683917 -1.0768874 -0.9997828]]
6 5
[[-0.999984   -0.90292215 -1.0021529  -1.0138396 ]]
6 6
[[-0.97037697 -0.16690703 -0.86765337 -0.55039155]]
6 7
[[-0.7162032   0.19970477 -0.07064095  0.11942437]]
6 8
[[0.05079344 0.23187602 0.35142076 0.2286213 ]]
7 1
[[1.2873458 0.998648  1.2683631 1.3356023]]
7 2
[[1.2791107  0.64501864 0.5724543  1.0765449 ]]
7 3
[[ 0.99733245 -0.9973949  -0.86626816  0.75278944]]
7 4
[[-0.18260962 -1.1134107  -1.066426   -0.2525822 ]]
7 5
[[-0.99915063 -1.00783    -1.0495683  -1.0049343 ]]
7 6
[[-0.8368877   0.15704954 -0.7461274  -0.2783414 ]]
7 7
[[-0.4762119   0.24403508  0.29704243  0.2522127 ]]
7 8
[[0.25708532 0.24363485 0.359121   0.26874906]]
8 1
[[1.3278843 1.3289572 1.3603956 1.32449  ]]
8 2
[[1.329405  1.200893  0.9991415 1.1561198]]
8 3
[[ 1.2858294   0.7070968  -0.11415845  0.7567332 ]]
8 4
[[ 1.0616183  -0.8390164  -0.99318993  0.66020614]]
8 5
[[ 0.33894807 -0.5019119  -0.904

3.884760008077137e-05.0.0007680822745896876.0.00012824294390156865.0.00027836693334393203.2.6804777007782832e-05.0.000165293226018548.0.00012496561976149678.2.167853199352976e-05.0.00026073891785927117.0.00013103093078825623.EPOCH: 10
这是第430局游戏，我赢了
最后20盘的胜率为0.55
这是第431局游戏，我赢了
最后20盘的胜率为0.55
这是第432局游戏，我赢了
最后20盘的胜率为0.55
这是第433局游戏，我赢了
最后20盘的胜率为0.55
0.0002287963725393638.2.0874223991995677e-05.0.001135586528107524.2.3909276933409274e-05.9.686697922006715e-06.3.4128446714021266e-05.1.9161070667905733e-05.0.0002769879065454006.2.769919046841096e-05.0.0010485081002116203.EPOCH: 10
这是第434局游戏，我赢了
最后20盘的胜率为0.55
6.861775909783319e-05.0.00010890587145695463.0.0008370594587177038.5.282629354042001e-05.2.3540287656942382e-05.5.1083719881717116e-05.6.217053851287346e-06.6.680017122562276e-06.0.0001921308576129377.0.0003375934611540288.EPOCH: 10
这是第435局游戏，我赢了
最后20盘的胜率为0.6
这是第436局游戏，我死了
最后20盘的胜率为0.6
3.930009188479744e-05.0.0005602521123364568.0.0003145897062495351.3.0022878490854055e-05.0.00023820922069

SystemExit: 

d:\miniconda3\lib\site-packages\IPython\core\interactiveshell.py:3561: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
