In [1]:
import pygame
import sys
import numpy as np
import random
import pandas as pd
import time
import tensorflow as tf
from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession

config = ConfigProto()
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)



pygame 2.1.2 (SDL 2.0.18, Python 3.7.6)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
width=10
height=10
pixel_size=(50,50)
display_size=(pixel_size[0]*width,pixel_size[1]*height)
record=[]
game_num=1
p=0
step=0
BATCH_SIZE=128
gamma=0.95
reward=[0]

color_dict={
    "wall":(177,177,177),
    "target":(0,177,0),
    "normal":(255,255,255),
    "start":(177,0,0)
}

map_dict={
    "target":(7,2),
    "start":(2,height-1),
    "tank1":(7,4),
    "tank2":(5,2),
    "tank3":(random.randint(3,width-3),random.randint(2,height-3)),

   }

wall_location=[]
for w in range(width):
    wall_location.append((w,0))
    wall_location.append((w,height-1))
    
for h in range(height):    
    wall_location.append((0,h))
    wall_location.append((width-1,h))
    
wall_location.remove(map_dict.get("start"))
wall_location.append((map_dict.get("start")[0],map_dict.get("start")[1]+1))
map_dict['wall']=wall_location


df=pd.DataFrame(columns=['s1','s2','a','s1_','s2_','r'])


a_dict={
    0:'up',
    1:'down',
    2:'left',
    3:'right'
}

s_index={}
for i in range(width-2):
    for j in range(height-2):
        s_index.update({(i+1,j+1):(i+(j*(width-2)))})
s_index.update({map_dict.get("start"):(width-2)*(height-2)})   


In [3]:
def draw_map():
    for i in range(width*height):
        w=i-width*(i//width)
        h=i//width
        
        if (w,h)==map_dict.get("target"):
            color=color_dict.get("target")
        elif (w,h)==map_dict.get("start"):
            color=color_dict.get("start")
        elif (w,h) in map_dict.get("wall"):
            color=color_dict.get("wall")
        else:
            color=color_dict.get("normal")
        
        pygame.draw.rect(game_map,color,(w*50,h*50,pixel_size[0],pixel_size[1]))

 

In [4]:
class tank(pygame.sprite.Sprite):
    def __init__(self,filename,location):
        pygame.sprite.Sprite.__init__(self)
        self.image = pygame.image.load(filename).convert()
        self.image = pygame.transform.scale(self.image,(50,50))

        self.rect = self.image.get_rect()
        self.rect.topleft=(location[0]*pixel_size[0],location[1]*pixel_size[1])
        

def crash_detect(sprite1,sprite2):
    global game_num
    global game_state
    result=pygame.sprite.collide_mask(sprite1,sprite2)
    
    if result:
        if sprite2 in tank_group:
            print("这是第{}局游戏，我死了".format(game_num))
            if game_num>20:
                print('最后20盘的胜率为{}'.format(record[-20:].count(1)/20))
            record.append(0)
            reward.append(-1)

        elif sprite2 in princess_group:
            print("这是第{}局游戏，我赢了".format(game_num))
            if game_num>20:
                print('最后20盘的胜率为{}'.format(record[-20:].count(1)/20))
            record.append(1)
            reward.append(10)


        game_num+=1
        game_state=1


def crash_wall():
    if (person_site[0],person_site[1]) in map_dict.get("wall"):
        #reward.append(-1.0)
        return True
    else:
        #reward.append(-0.02)
        return False
    
    
def move(direction):
    global person_site
    global step
    if direction=='up':
        person_site[1]-=1
        a= crash_wall()
        if a==True:
            person_site[1]+=1
        
    if direction=='down':
        person_site[1]+=1
        a= crash_wall()
        if a==True:
            person_site[1]-=1
    if direction=='left':
        person_site[0]-=1
        a= crash_wall()
        if a==True:
            person_site[0]+=1
    if direction=='right':
        person_site[0]+=1
        a= crash_wall()
        if a==True:
            person_site[0]-=1
        
    person.rect=(person_site[0]*pixel_size[0],person_site[1]*pixel_size[1],50,50)
    crash_detect(person,tank1)       
    crash_detect(person,tank2)   
    crash_detect(person,tank3)       

    crash_detect(person,princess)         
    step+=1

    
def reset():
    global person_site
    global game_state
    person_site=[map_dict.get("start")[0],map_dict.get("start")[1]]
    person.rect=(person_site[0]*pixel_size[0],person_site[1]*pixel_size[1],50,50)
    game_state=0
    reward.append(-0.02)
    
    if game_num>70 and game_num%20==0:    
        pgdebug()   

In [5]:
def pick_a(state):    
    p=model.predict([state])
    a=np.random.choice(p.shape[1],p=p.ravel())
    return a
        
    
def trace_collect(s1,s2,a,s1_,s2_,r):   
    global df
    new_trace={
        's1':s1,
        's2':s2,
        'a':a,
        's1_':s1_,
        's2_':s2_,
        'r':r
    }
    df=df.append(new_trace,ignore_index=True)
    
    
def preprocessing():
    global df
    train_ds=df
    dr=0
    n=len(train_ds['r'])
    for t in range(n):
        k=n-t-1
        dr=dr*gamma+train_ds['r'][k]
        train_ds['r'][k]=dr    
        
    df=pd.DataFrame(columns=['s1','s2','a','s1_','s2_','r'])
    #print(train_ds)
    return train_ds


def train_step(train_ds):
    global BATCH_SIZE
    BATCH_SIZE=len(train_ds)
    s = np.int32(np.stack((train_ds['s1'],train_ds['s2']),1))
    a = np.array(train_ds['a'])
    s_ = np.int32(np.stack((train_ds['s1_'],train_ds['s2_']),1))
    r = np.array(train_ds['r'])
    
    

   
    with tf.GradientTape(persistent=True) as tape:
        #loss函数
        q=model(s)        
        loss=tf.keras.losses.sparse_categorical_crossentropy(a,q)        
        loss=r*loss        
        
    gradient=tape.gradient(loss,model.trainable_variables)
    opt.apply_gradients(zip(gradient,model.trainable_variables))
    del tape
    
    
def one_turn():
    s1=int(person_site[0])
    s2=int(person_site[1])
    a=pick_a([s1,s2])
    move(a_dict.get(a))
    s1_=int(person_site[0])
    s2_=int(person_site[1])
    r=reward[-1]
    trace_collect(s1,s2,a,s1_,s2_,r)
                
    if game_state==1:          
        train_ds=preprocessing()
        train_step(train_ds)
        reset()


In [6]:
model=tf.keras.Sequential([
    tf.keras.layers.Dense(128,input_shape=(BATCH_SIZE,2),activation='relu'),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dense(4,activation='softmax')       #a,qmax=r+gamma*q_max
   ]
)


opt=tf.keras.optimizers.Adam(learning_rate=0.0001)

In [7]:
def pgdebug():
    for i in range(width-2):
        for j in range(height-2):
            result=model.predict([[i+1,j+1]])
            print(i+1,j+1)
            print(result)


In [8]:
pygame.init()
clock = pygame.time.Clock()
pygame.display.set_caption("AI训练游戏")

screen = pygame.display.set_mode(display_size)
game_map=pygame.surface.Surface(display_size)
draw_map()

tank_group = pygame.sprite.Group()
princess_group = pygame.sprite.Group()
person_group=pygame.sprite.Group()

tank1 = tank("img/tank.jpg",map_dict.get("tank1"))
tank2 = tank("img/tank.jpg",map_dict.get("tank2"))
tank3 = tank("img/tank.jpg",map_dict.get("tank3"))

tank_group.add(tank1)
tank_group.add(tank2)
tank_group.add(tank3)


princess=tank('img/sidalin.jpeg',map_dict.get("target"))
princess_group.add(princess)

person_site=[map_dict.get("start")[0],map_dict.get("start")[1]]
person=tank('img/maintank.jpeg',person_site)
person_group.add(person)

reset()

while True:
    clock.tick(60)

    screen.blit(game_map,(0,0))
    tank_group.draw(screen)
    princess_group.draw(screen)
    screen.blit(person.image,person.rect)
    
    
    
    one_turn()



        
    for event in pygame.event.get():
        if event.type ==pygame.QUIT:
            pygame.quit()
            sys.exit()
            

        
#       if event.type ==pygame.KEYDOWN:
#           if event.key == pygame.K_UP:
#               move('up')
#           if event.key == pygame.K_DOWN:
#               move('down')
#           if event.key == pygame.K_LEFT:
#               move('left')
#           if event.key == pygame.K_RIGHT:
#               move('right')
#           if event.key == pygame.K_SPACE:
                
                
     
    pygame.display.update()

这是第1局游戏，我死了
这是第2局游戏，我死了
这是第3局游戏，我死了
这是第4局游戏，我死了
这是第5局游戏，我死了
这是第6局游戏，我死了
这是第7局游戏，我死了
这是第8局游戏，我赢了
这是第9局游戏，我死了
这是第10局游戏，我死了
这是第11局游戏，我死了
这是第12局游戏，我死了
这是第13局游戏，我死了
这是第14局游戏，我死了
这是第15局游戏，我死了
这是第16局游戏，我死了
这是第17局游戏，我死了
这是第18局游戏，我死了
这是第19局游戏，我死了
这是第20局游戏，我死了
这是第21局游戏，我死了
最后20盘的胜率为0.05
这是第22局游戏，我死了
最后20盘的胜率为0.05
这是第23局游戏，我死了
最后20盘的胜率为0.05
这是第24局游戏，我死了
最后20盘的胜率为0.05
这是第25局游戏，我死了
最后20盘的胜率为0.05
这是第26局游戏，我死了
最后20盘的胜率为0.05
这是第27局游戏，我死了
最后20盘的胜率为0.05
这是第28局游戏，我死了
最后20盘的胜率为0.05
这是第29局游戏，我死了
最后20盘的胜率为0.0
这是第30局游戏，我死了
最后20盘的胜率为0.0
这是第31局游戏，我死了
最后20盘的胜率为0.0
这是第32局游戏，我死了
最后20盘的胜率为0.0
这是第33局游戏，我死了
最后20盘的胜率为0.0
这是第34局游戏，我死了
最后20盘的胜率为0.0
这是第35局游戏，我死了
最后20盘的胜率为0.0
这是第36局游戏，我死了
最后20盘的胜率为0.0
这是第37局游戏，我死了
最后20盘的胜率为0.0
这是第38局游戏，我死了
最后20盘的胜率为0.0
这是第39局游戏，我死了
最后20盘的胜率为0.0
这是第40局游戏，我死了
最后20盘的胜率为0.0
这是第41局游戏，我死了
最后20盘的胜率为0.0
这是第42局游戏，我死了
最后20盘的胜率为0.0
这是第43局游戏，我死了
最后20盘的胜率为0.0
这是第44局游戏，我死了
最后20盘的胜率为0.0
这是第45局游戏，我死了
最后20盘的胜率为0.0
这是第46局游戏，我赢了
最后20盘的胜率为0.0
这是第47局游戏，我死了
最后20盘的胜率为0.05
这是第48局游戏，我死了
最后20盘的胜率为0.05
这是第49局游戏，我死

6 5
[[0.2707193  0.21894267 0.25412625 0.25621182]]
6 6
[[0.27811944 0.2181779  0.2580183  0.24568434]]
6 7
[[0.2831517  0.2162848  0.25908697 0.24147654]]
6 8
[[0.29011136 0.21362257 0.2566388  0.23962723]]
7 1
[[0.25749087 0.21180445 0.22802599 0.3026787 ]]
7 2
[[0.2603921  0.20964497 0.23003776 0.29992518]]
7 3
[[0.2615307  0.20920266 0.23551369 0.2937529 ]]
7 4
[[0.26278123 0.21121472 0.2404314  0.28557265]]
7 5
[[0.26747653 0.21198048 0.24949892 0.2710441 ]]
7 6
[[0.27525097 0.21484762 0.25559852 0.2543029 ]]
7 7
[[0.28234836 0.21348657 0.2592536  0.2449115 ]]
7 8
[[0.2874052  0.21163511 0.26035565 0.240604  ]]
8 1
[[0.25771147 0.20715119 0.2246999  0.31043744]]
8 2
[[0.26089382 0.20502105 0.22591105 0.308174  ]]
8 3
[[0.26219815 0.20385453 0.23095699 0.30299035]]
8 4
[[0.26333356 0.20511483 0.23596586 0.29558575]]
8 5
[[0.2652912  0.20702477 0.24226533 0.2854187 ]]
8 6
[[0.2715968  0.20767923 0.2513427  0.2693813 ]]
8 7
[[0.27962694 0.21062875 0.25704733 0.25269696]]
8 8
[[0.2866

7 6
[[0.30182168 0.18312794 0.21716219 0.2978882 ]]
7 7
[[0.30622056 0.18235257 0.2241223  0.28730452]]
7 8
[[0.31011915 0.18014884 0.23024446 0.27948752]]
8 1
[[0.2792022  0.19155195 0.18387529 0.34537056]]
8 2
[[0.28264588 0.18642944 0.18233617 0.34858856]]
8 3
[[0.28952828 0.18135355 0.18421143 0.3449067 ]]
8 4
[[0.2953806  0.17761566 0.18882419 0.33817956]]
8 5
[[0.29693013 0.17823826 0.19552729 0.3293043 ]]
8 6
[[0.30238283 0.17584705 0.20614658 0.31562352]]
8 7
[[0.30925733 0.17526591 0.21358328 0.30189344]]
8 8
[[0.31356877 0.17432867 0.22040565 0.2916969 ]]
这是第140局游戏，我死了
最后20盘的胜率为0.3
这是第141局游戏，我死了
最后20盘的胜率为0.3
这是第142局游戏，我赢了
最后20盘的胜率为0.25
这是第143局游戏，我赢了
最后20盘的胜率为0.3
这是第144局游戏，我死了
最后20盘的胜率为0.35
这是第145局游戏，我死了
最后20盘的胜率为0.3
这是第146局游戏，我死了
最后20盘的胜率为0.25
这是第147局游戏，我死了
最后20盘的胜率为0.25
这是第148局游戏，我赢了
最后20盘的胜率为0.25
这是第149局游戏，我死了
最后20盘的胜率为0.25
这是第150局游戏，我死了
最后20盘的胜率为0.25
这是第151局游戏，我死了
最后20盘的胜率为0.25
这是第152局游戏，我死了
最后20盘的胜率为0.25
这是第153局游戏，我死了
最后20盘的胜率为0.25
这是第154局游戏，我赢了
最后20盘的胜率为0.2
这是第155局游戏，我死了

8 7
[[0.33761904 0.08620229 0.12092219 0.45525655]]
8 8
[[0.34315977 0.08265227 0.12125604 0.45293188]]
这是第180局游戏，我死了
最后20盘的胜率为0.2
这是第181局游戏，我死了
最后20盘的胜率为0.2
这是第182局游戏，我死了
最后20盘的胜率为0.2
这是第183局游戏，我死了
最后20盘的胜率为0.2
这是第184局游戏，我死了
最后20盘的胜率为0.2
这是第185局游戏，我死了
最后20盘的胜率为0.2
这是第186局游戏，我赢了
最后20盘的胜率为0.2
这是第187局游戏，我死了
最后20盘的胜率为0.25
这是第188局游戏，我赢了
最后20盘的胜率为0.2
这是第189局游戏，我死了
最后20盘的胜率为0.2
这是第190局游戏，我死了
最后20盘的胜率为0.2
这是第191局游戏，我赢了
最后20盘的胜率为0.2
这是第192局游戏，我死了
最后20盘的胜率为0.25
这是第193局游戏，我死了
最后20盘的胜率为0.25
这是第194局游戏，我死了
最后20盘的胜率为0.2
这是第195局游戏，我死了
最后20盘的胜率为0.2
这是第196局游戏，我死了
最后20盘的胜率为0.2
这是第197局游戏，我死了
最后20盘的胜率为0.2
这是第198局游戏，我死了
最后20盘的胜率为0.2
这是第199局游戏，我死了
最后20盘的胜率为0.2
1 1
[[0.2816204  0.1985617  0.22245876 0.29735914]]
1 2
[[0.28914264 0.18703757 0.21893205 0.30488774]]
1 3
[[0.2983452  0.17363557 0.21223484 0.31578442]]
1 4
[[0.30747947 0.160832   0.20509027 0.32659823]]
1 5
[[0.31641793 0.14853255 0.19778548 0.337264  ]]
1 6
[[0.3251124  0.13703926 0.19062278 0.34722555]]
1 7
[[0.3335695  0.12615195 0.18357755 0.

这是第233局游戏，我死了
最后20盘的胜率为0.25
这是第234局游戏，我死了
最后20盘的胜率为0.2
这是第235局游戏，我死了
最后20盘的胜率为0.15
这是第236局游戏，我死了
最后20盘的胜率为0.15
这是第237局游戏，我赢了
最后20盘的胜率为0.15
这是第238局游戏，我死了
最后20盘的胜率为0.2
这是第239局游戏，我死了
最后20盘的胜率为0.15
1 1
[[0.2888328  0.19368272 0.23050816 0.2869763 ]]
1 2
[[0.30092442 0.18047693 0.22566414 0.29293454]]
1 3
[[0.31315178 0.16711895 0.21995008 0.29977918]]
1 4
[[0.3259738  0.15418166 0.21380438 0.30604017]]
1 5
[[0.33855012 0.14167418 0.20742439 0.31235132]]
1 6
[[0.35082632 0.12970766 0.20075026 0.31871575]]
1 7
[[0.36304548 0.11842643 0.19378024 0.32474783]]
1 8
[[0.37498897 0.10787468 0.18668383 0.33045256]]
2 1
[[0.3027479  0.17201973 0.21898864 0.3062437 ]]
2 2
[[0.31471753 0.1590635  0.21549542 0.31072354]]
2 3
[[0.32609305 0.1479224  0.209797   0.31618756]]
2 4
[[0.33820713 0.13678311 0.204574   0.3204358 ]]
2 5
[[0.34999654 0.12563336 0.19793417 0.32643586]]
2 6
[[0.3617953  0.11555073 0.19156349 0.33109048]]
2 7
[[0.37400225 0.10608479 0.18491966 0.3349933 ]]
2 8
[[0.3861302  0.0966757

1 6
[[0.39197922 0.10852582 0.15946744 0.34002748]]
1 7
[[0.40823126 0.09585056 0.14829652 0.34762168]]
1 8
[[0.42379463 0.08439609 0.13750657 0.3543027 ]]
2 1
[[0.31313112 0.16783027 0.20191771 0.31712097]]
2 2
[[0.33687377 0.14793861 0.18863694 0.32655063]]
2 3
[[0.35463142 0.13339959 0.17777832 0.33419064]]
2 4
[[0.37297788 0.11984274 0.16779837 0.33938107]]
2 5
[[0.39086542 0.10733315 0.15744928 0.34435216]]
2 6
[[0.40823328 0.09568638 0.14722855 0.3488518 ]]
2 7
[[0.42442903 0.08479064 0.13722955 0.35355076]]
2 8
[[0.43991002 0.074412   0.12680611 0.3588719 ]]
3 1
[[0.31614846 0.15621737 0.1921747  0.33545947]]
3 2
[[0.34777978 0.13076027 0.1751539  0.34630606]]
3 3
[[0.36890095 0.11524736 0.16303487 0.35281682]]
3 4
[[0.38602766 0.10288758 0.15213963 0.3589451 ]]
3 5
[[0.4022158  0.09216877 0.1430825  0.3625329 ]]
3 6
[[0.41969338 0.08204297 0.13359042 0.36467323]]
3 7
[[0.43612128 0.07280668 0.12410817 0.36696386]]
3 8
[[0.45239335 0.06437104 0.11511758 0.368118  ]]
4 1
[[0.3189

3 2
[[0.30000982 0.13686179 0.16804652 0.3950819 ]]
3 3
[[0.33252597 0.11483938 0.15028356 0.40235108]]
3 4
[[0.3565951  0.09990448 0.13714214 0.4063583 ]]
3 5
[[0.37408653 0.08752757 0.12520272 0.41318318]]
3 6
[[0.389632   0.07649664 0.1139167  0.41995475]]
3 7
[[0.4048579  0.06656335 0.10295115 0.42562753]]
3 8
[[0.42055458 0.05789481 0.09290121 0.42864937]]
4 1
[[0.25870454 0.1567435  0.17472531 0.40982664]]
4 2
[[0.2836393  0.1264059  0.1573048  0.43265003]]
4 3
[[0.31764933 0.10475163 0.13993597 0.4376631 ]]
4 4
[[0.34765524 0.08724533 0.12395242 0.441147  ]]
4 5
[[0.37027648 0.07522693 0.1122364  0.44226018]]
4 6
[[0.3883211  0.06536569 0.10165942 0.44465384]]
4 7
[[0.4020427  0.05681435 0.09197266 0.44917032]]
4 8
[[0.41465533 0.04932732 0.08303604 0.45298138]]
5 1
[[0.25289515 0.1454036  0.16220048 0.43950078]]
5 2
[[0.26742783 0.11877024 0.14693362 0.46686822]]
5 3
[[0.2989054  0.09568364 0.12989369 0.47551727]]
5 4
[[0.33018303 0.07847308 0.11410137 0.4772425 ]]
5 5
[[0.3576

4 6
[[0.3582024  0.05496791 0.08095852 0.50587124]]
4 7
[[0.36650842 0.04728237 0.07157642 0.51463276]]
4 8
[[0.37487188 0.04042577 0.06318692 0.52151537]]
5 1
[[0.24557279 0.13483463 0.16165929 0.45793325]]
5 2
[[0.2616705  0.10013656 0.13083881 0.50735414]]
5 3
[[0.28398898 0.07837211 0.10696665 0.5306723 ]]
5 4
[[0.30828342 0.06376228 0.09043948 0.5375148 ]]
5 5
[[0.326387   0.05262066 0.07819133 0.542801  ]]
5 6
[[0.3410284  0.04463329 0.06879427 0.545544  ]]
5 7
[[0.35473594 0.03844371 0.06114828 0.54567206]]
5 8
[[0.362628   0.03297528 0.05387279 0.550524  ]]
6 1
[[0.23600334 0.1256057  0.15133004 0.4870609 ]]
6 2
[[0.24734618 0.09237657 0.12294991 0.53732735]]
6 3
[[0.26318675 0.06896693 0.09735124 0.57049507]]
6 4
[[0.28525802 0.05514504 0.08074514 0.5788518 ]]
6 5
[[0.30528638 0.04467689 0.06820036 0.58183634]]
6 6
[[0.3207083  0.03674138 0.05881641 0.5837339 ]]
6 7
[[0.33242258 0.030919   0.05142029 0.58523816]]
6 8
[[0.3459314  0.02652515 0.04544354 0.5820999 ]]
7 1
[[0.2261

6 2
[[0.2552087  0.11316973 0.15718578 0.47443578]]
6 3
[[0.27814692 0.07387027 0.11113656 0.5368462 ]]
6 4
[[0.2968569  0.05309833 0.08324648 0.56679827]]
6 5
[[0.30689618 0.0422641  0.06816454 0.5826751 ]]
6 6
[[0.31328863 0.03493876 0.05854984 0.5932228 ]]
6 7
[[0.32112357 0.02883822 0.05029879 0.5997394 ]]
6 8
[[0.33147472 0.02458414 0.04424702 0.5996941 ]]
7 1
[[0.22392544 0.16105276 0.18887109 0.4261507 ]]
7 2
[[0.24175566 0.11419708 0.15834327 0.48570397]]
7 3
[[0.25982335 0.07312348 0.11364486 0.5534083 ]]
7 4
[[0.2804122  0.04759831 0.07834819 0.59364134]]
7 5
[[0.28985348 0.03633475 0.06159816 0.61221355]]
7 6
[[0.2974248  0.02890951 0.05052984 0.6231358 ]]
7 7
[[0.30227676 0.0238201  0.04329069 0.63061243]]
7 8
[[0.30788863 0.01952808 0.03697689 0.63560635]]
8 1
[[0.2170268  0.15469246 0.18182781 0.4464529 ]]
8 2
[[0.22839963 0.1153767  0.15826695 0.49795672]]
8 3
[[0.24546143 0.07264659 0.11534417 0.5665478 ]]
8 4
[[0.2602041  0.04592812 0.07828525 0.6155825 ]]
8 5
[[0.2734

7 6
[[0.5048383  0.01685241 0.03976924 0.4385401 ]]
7 7
[[0.5229261  0.01301244 0.03326743 0.4307941 ]]
7 8
[[0.5384298  0.01014945 0.02790274 0.42351803]]
8 1
[[0.25774544 0.13228586 0.19722232 0.4127463 ]]
8 2
[[0.30251166 0.08061746 0.14231049 0.47456047]]
8 3
[[0.3650985  0.0447033  0.08750312 0.5026951 ]]
8 4
[[0.42714965 0.02657723 0.05706241 0.48921067]]
8 5
[[0.4735758  0.01807561 0.04189293 0.46645567]]
8 6
[[0.5009675  0.01369117 0.03385404 0.45148727]]
8 7
[[0.52130383 0.01050992 0.02819489 0.43999138]]
8 8
[[0.5380319  0.00807425 0.02345871 0.43043512]]
这是第440局游戏，我死了
最后20盘的胜率为0.25
这是第441局游戏，我死了
最后20盘的胜率为0.2
这是第442局游戏，我死了
最后20盘的胜率为0.2
这是第443局游戏，我赢了
最后20盘的胜率为0.2
这是第444局游戏，我死了
最后20盘的胜率为0.2
这是第445局游戏，我死了
最后20盘的胜率为0.2
这是第446局游戏，我死了
最后20盘的胜率为0.2
这是第447局游戏，我赢了
最后20盘的胜率为0.2
这是第448局游戏，我死了
最后20盘的胜率为0.25
这是第449局游戏，我死了
最后20盘的胜率为0.25
这是第450局游戏，我赢了
最后20盘的胜率为0.25
这是第451局游戏，我死了
最后20盘的胜率为0.3
这是第452局游戏，我赢了
最后20盘的胜率为0.3
这是第453局游戏，我死了
最后20盘的胜率为0.3
这是第454局游戏，我死了
最后20盘的胜率为0.3
这是第455局游戏，我死了
最后20盘

8 8
[[0.7022569  0.00493421 0.01164078 0.2811681 ]]
这是第480局游戏，我死了
最后20盘的胜率为0.55
这是第481局游戏，我赢了
最后20盘的胜率为0.55
这是第482局游戏，我死了
最后20盘的胜率为0.55
这是第483局游戏，我死了
最后20盘的胜率为0.55
这是第484局游戏，我赢了
最后20盘的胜率为0.5
这是第485局游戏，我死了
最后20盘的胜率为0.5
这是第486局游戏，我死了
最后20盘的胜率为0.45
这是第487局游戏，我死了
最后20盘的胜率为0.45
这是第488局游戏，我赢了
最后20盘的胜率为0.45
这是第489局游戏，我死了
最后20盘的胜率为0.5
这是第490局游戏，我死了
最后20盘的胜率为0.45
这是第491局游戏，我死了
最后20盘的胜率为0.45
这是第492局游戏，我赢了
最后20盘的胜率为0.45
这是第493局游戏，我死了
最后20盘的胜率为0.5
这是第494局游戏，我死了
最后20盘的胜率为0.45
这是第495局游戏，我死了
最后20盘的胜率为0.4
这是第496局游戏，我赢了
最后20盘的胜率为0.35
这是第497局游戏，我赢了
最后20盘的胜率为0.35
这是第498局游戏，我死了
最后20盘的胜率为0.35
这是第499局游戏，我赢了
最后20盘的胜率为0.35
1 1
[[0.3167213  0.18166864 0.19008008 0.31152996]]
1 2
[[0.34948078 0.15701936 0.16821241 0.32528743]]
1 3
[[0.37821305 0.13538237 0.14882755 0.33757707]]
1 4
[[0.40512425 0.11563828 0.1305407  0.34869686]]
1 5
[[0.43109688 0.097652   0.11328047 0.35797068]]
1 6
[[0.45530784 0.08186289 0.09765735 0.36517197]]
1 7
[[0.47807097 0.06806858 0.0835752  0.3702852 ]]
1 8
[[0.4990935  0.05626071 0

这是第534局游戏，我死了
最后20盘的胜率为0.05
这是第535局游戏，我死了
最后20盘的胜率为0.05
这是第536局游戏，我死了
最后20盘的胜率为0.05
这是第537局游戏，我死了
最后20盘的胜率为0.05
这是第538局游戏，我死了
最后20盘的胜率为0.05
这是第539局游戏，我赢了
最后20盘的胜率为0.05
1 1
[[0.30650085 0.19708055 0.20516232 0.2912563 ]]
1 2
[[0.3317087  0.17952727 0.19220565 0.2965584 ]]
1 3
[[0.35412556 0.16334483 0.17963664 0.30289295]]
1 4
[[0.37718764 0.14748164 0.16683996 0.30849075]]
1 5
[[0.40057647 0.13219671 0.15371427 0.3135126 ]]
1 6
[[0.42366502 0.11790789 0.14096715 0.31745997]]
1 7
[[0.44637987 0.10467551 0.12871747 0.32022718]]
1 8
[[0.46854067 0.09250947 0.11708952 0.3218604 ]]
2 1
[[0.29450753 0.19245479 0.19913621 0.31390145]]
2 2
[[0.35099426 0.1613938  0.17426439 0.31334752]]
2 3
[[0.37815884 0.14521253 0.16142824 0.31520036]]
2 4
[[0.40191388 0.1303507  0.14994085 0.31779462]]
2 5
[[0.42363888 0.11742886 0.13863333 0.32029894]]
2 6
[[0.44541454 0.1047946  0.12726156 0.3225293 ]]
2 7
[[0.4667394  0.09324857 0.1163707  0.3236413 ]]
2 8
[[0.4880348  0.08232061 0.1056414  0.3240032 ]]


2 4
[[0.44228107 0.11857296 0.13534439 0.3038016 ]]
2 5
[[0.4705658  0.10440996 0.12226996 0.30275428]]
2 6
[[0.49853227 0.09112721 0.10988262 0.30045792]]
2 7
[[0.52686596 0.07876735 0.09756413 0.2968026 ]]
2 8
[[0.5545929  0.06758793 0.08596766 0.2918515 ]]
3 1
[[0.3322074  0.16477332 0.16685    0.33616933]]
3 2
[[0.39887837 0.1350095  0.14430065 0.32181147]]
3 3
[[0.43564856 0.1175622  0.13078836 0.31600082]]
3 4
[[0.46948487 0.10250816 0.11798186 0.31002513]]
3 5
[[0.4990181  0.08950358 0.10643303 0.30504522]]
3 6
[[0.5269828  0.0776848  0.09504935 0.30028307]]
3 7
[[0.5527205  0.06743675 0.08458609 0.29525664]]
3 8
[[0.5775005  0.05824276 0.07512077 0.28913593]]
4 1
[[0.3092658  0.16884108 0.16945243 0.35244069]]
4 2
[[0.41009235 0.12046966 0.12827936 0.34115866]]
4 3
[[0.45452452 0.10329044 0.1148864  0.3272986 ]]
4 4
[[0.48946497 0.08895363 0.10272764 0.31885374]]
4 5
[[0.52236    0.07656503 0.09146675 0.30960822]]
4 6
[[0.55105466 0.06626495 0.08192903 0.30075133]]
4 7
[[0.5775

3 8
[[0.6793054  0.04154071 0.05466473 0.22448923]]
4 1
[[0.35421932 0.1554826  0.14835578 0.34194225]]
4 2
[[0.4803508  0.1033752  0.10980994 0.30646408]]
4 3
[[0.53363276 0.08554843 0.09622012 0.28459865]]
4 4
[[0.576503   0.0709275  0.08354156 0.26902798]]
4 5
[[0.6149817  0.05900568 0.07194467 0.2540679 ]]
4 6
[[0.6490679  0.04945441 0.0624103  0.23906742]]
4 7
[[0.68045896 0.04090549 0.05327114 0.22536437]]
4 8
[[0.7092535  0.03356102 0.04500778 0.21217765]]
5 1
[[0.32752588 0.1632349  0.15044723 0.35879204]]
5 2
[[0.4884509  0.09277812 0.09678238 0.32198858]]
5 3
[[0.5567576  0.07274682 0.08056723 0.28992835]]
5 4
[[0.6040157  0.05945376 0.07006179 0.26646873]]
5 5
[[0.6423733  0.04864202 0.05978807 0.24919659]]
5 6
[[0.6768637  0.03984328 0.05071985 0.23257318]]
5 7
[[0.70748305 0.03303748 0.0434813  0.21599816]]
5 8
[[0.7349251  0.02715592 0.03701056 0.20090838]]
6 1
[[0.30681753 0.17149536 0.15373269 0.36795446]]
6 2
[[0.47785425 0.08785408 0.08887363 0.34541807]]
6 3
[[0.5739

5 4
[[0.44084376 0.03560112 0.03803873 0.48551637]]
5 5
[[0.4759713  0.02646915 0.02872592 0.46883366]]
5 6
[[0.5047196  0.02000345 0.02212043 0.45315647]]
5 7
[[0.531038   0.01539929 0.01718097 0.43638173]]
5 8
[[0.55303293 0.01178101 0.0131999  0.4219861 ]]
6 1
[[0.22689708 0.19833583 0.1849863  0.3897808 ]]
6 2
[[0.28408024 0.10523938 0.11057927 0.50010115]]
6 3
[[0.36627096 0.04495684 0.04931574 0.5394565 ]]
6 4
[[0.41839486 0.02924215 0.03186821 0.5204948 ]]
6 5
[[0.45920002 0.02138045 0.02322671 0.49619287]]
6 6
[[0.4899225  0.01583597 0.01750177 0.47673973]]
6 7
[[0.5163663  0.01185269 0.01334703 0.45843402]]
6 8
[[0.5420094  0.00908007 0.01033821 0.43857235]]
7 1
[[0.21937126 0.19725002 0.18166643 0.40171227]]
7 2
[[0.25587687 0.12139867 0.12343981 0.49928468]]
7 3
[[0.3244805  0.04882924 0.05342999 0.57326025]]
7 4
[[0.3935468  0.0247894  0.02771307 0.55395067]]
7 5
[[0.43317404 0.01747091 0.01929259 0.53006244]]
7 6
[[0.4714828  0.0127277  0.01405973 0.5017298 ]]
7 7
[[0.4999

6 7
[[0.6691907  0.00550601 0.00606357 0.31923974]]
6 8
[[0.69170874 0.00397382 0.00439313 0.2999243 ]]
7 1
[[0.21748894 0.21591456 0.1823035  0.384293  ]]
7 2
[[0.2831768  0.09073142 0.08972739 0.53636444]]
7 3
[[0.4170554  0.02699259 0.02797328 0.5279787 ]]
7 4
[[0.53333217 0.01284349 0.0137576  0.44006675]]
7 5
[[0.59787273 0.0084731  0.00917192 0.38448218]]
7 6
[[0.6432605  0.00580352 0.00633585 0.3446002 ]]
7 7
[[0.67189026 0.00405065 0.00447838 0.31958064]]
7 8
[[0.69635314 0.00283637 0.00317619 0.29763436]]
8 1
[[0.21063004 0.21708931 0.18044789 0.39183268]]
8 2
[[0.2547608  0.11051192 0.10416061 0.53056663]]
8 3
[[0.35465023 0.03141595 0.03255296 0.58138084]]
8 4
[[0.49314377 0.01093254 0.01172264 0.48420104]]
8 5
[[0.5766858  0.00660877 0.00720302 0.40950242]]
8 6
[[0.63260865 0.0043809  0.00481525 0.35819525]]
8 7
[[0.6717754  0.00301836 0.00334667 0.32185954]]
8 8
[[0.6980199  0.0020935  0.00235219 0.29753438]]
这是第700局游戏，我死了
最后20盘的胜率为0.5
这是第701局游戏，我死了
最后20盘的胜率为0.45
这是第702局游戏

8 4
[[0.637202   0.00370715 0.00409313 0.35499766]]
8 5
[[0.6752393  0.00229073 0.00252957 0.3199404 ]]
8 6
[[0.7041799  0.00146166 0.00165154 0.292707  ]]
8 7
[[0.7267732  0.00094263 0.00108368 0.2712005 ]]
8 8
[[7.4499899e-01 5.9552636e-04 6.9116207e-04 2.5371432e-01]]
这是第740局游戏，我赢了
最后20盘的胜率为0.3
这是第741局游戏，我赢了
最后20盘的胜率为0.35
这是第742局游戏，我死了
最后20盘的胜率为0.35
这是第743局游戏，我死了
最后20盘的胜率为0.35
这是第744局游戏，我赢了
最后20盘的胜率为0.35
这是第745局游戏，我死了
最后20盘的胜率为0.35
这是第746局游戏，我死了
最后20盘的胜率为0.35
这是第747局游戏，我赢了
最后20盘的胜率为0.3
这是第748局游戏，我死了
最后20盘的胜率为0.35
这是第749局游戏，我死了
最后20盘的胜率为0.35
这是第750局游戏，我赢了
最后20盘的胜率为0.35
这是第751局游戏，我赢了
最后20盘的胜率为0.35
这是第752局游戏，我死了
最后20盘的胜率为0.4
这是第753局游戏，我死了
最后20盘的胜率为0.35
这是第754局游戏，我赢了
最后20盘的胜率为0.35
这是第755局游戏，我死了
最后20盘的胜率为0.4
这是第756局游戏，我赢了
最后20盘的胜率为0.4
这是第757局游戏，我赢了
最后20盘的胜率为0.45
这是第758局游戏，我赢了
最后20盘的胜率为0.45
这是第759局游戏，我赢了
最后20盘的胜率为0.5
1 1
[[0.41475636 0.1299088  0.12878174 0.3265531 ]]
1 2
[[0.48227274 0.0951684  0.09459738 0.32796153]]
1 3
[[0.54269904 0.06687765 0.06667647 0.32374683]]
1 4
[[0.59741575 0

这是第786局游戏，我赢了
最后20盘的胜率为0.2
这是第787局游戏，我赢了
最后20盘的胜率为0.25
这是第788局游戏，我死了
最后20盘的胜率为0.3
这是第789局游戏，我赢了
最后20盘的胜率为0.25
这是第790局游戏，我死了
最后20盘的胜率为0.3
这是第791局游戏，我赢了
最后20盘的胜率为0.3
这是第792局游戏，我赢了
最后20盘的胜率为0.35
这是第793局游戏，我死了
最后20盘的胜率为0.35
这是第794局游戏，我死了
最后20盘的胜率为0.3
这是第795局游戏，我死了
最后20盘的胜率为0.3
这是第796局游戏，我赢了
最后20盘的胜率为0.3
这是第797局游戏，我死了
最后20盘的胜率为0.35
这是第798局游戏，我死了
最后20盘的胜率为0.35
这是第799局游戏，我死了
最后20盘的胜率为0.35
1 1
[[0.34974945 0.14458872 0.1476214  0.35804042]]
1 2
[[0.3913723  0.11293267 0.11684351 0.37885144]]
1 3
[[0.4237896  0.08613507 0.0902858  0.3997895 ]]
1 4
[[0.4527662  0.06402368 0.06828207 0.41492808]]
1 5
[[0.47774932 0.04681383 0.05076607 0.42467082]]
1 6
[[0.49884668 0.03385154 0.03736506 0.42993662]]
1 7
[[0.51669586 0.02430703 0.02730306 0.43169406]]
1 8
[[0.5319148  0.01733034 0.01980798 0.4309469 ]]
2 1
[[0.2733925  0.16896954 0.16813205 0.3895059 ]]
2 2
[[0.41454676 0.08811909 0.09324305 0.40409112]]
2 3
[[0.45080897 0.06651028 0.07152151 0.4111592 ]]
2 4
[[0.4744881  0.04933366 0.05382521 0.42

1 6
[[0.531673   0.03568881 0.04000831 0.39262986]]
1 7
[[0.55510145 0.02586091 0.02955769 0.38947996]]
1 8
[[0.57604    0.01861213 0.0216891  0.38365877]]
2 1
[[0.29828    0.15603082 0.16990784 0.37578133]]
2 2
[[0.43751565 0.08860492 0.09534087 0.37853852]]
2 3
[[0.4720596  0.06796378 0.07417681 0.3857998 ]]
2 4
[[0.501533   0.05081347 0.05621343 0.39144012]]
2 5
[[0.5275581  0.03763191 0.04226607 0.39254394]]
2 6
[[0.5507591  0.02755453 0.03148816 0.3901982 ]]
2 7
[[0.5713947  0.01997026 0.02321905 0.38541594]]
2 8
[[0.5903262  0.01426686 0.0168917  0.37851524]]
3 1
[[0.21946917 0.23268649 0.22267957 0.32516474]]
3 2
[[0.41004    0.07833245 0.08800695 0.4236207 ]]
3 3
[[0.49848515 0.0511738  0.05734542 0.3929957 ]]
3 4
[[0.5275573  0.03810689 0.04336903 0.39096674]]
3 5
[[0.54953384 0.02832844 0.03269418 0.38944358]]
3 6
[[0.56987834 0.0206599  0.02416226 0.38529944]]
3 7
[[0.588158   0.01501875 0.01785367 0.37896964]]
3 8
[[0.6049002  0.01077578 0.0130405  0.3712835 ]]
4 1
[[0.2036

3 2
[[0.37805566 0.06100247 0.07432839 0.48661348]]
3 3
[[0.382195   0.04204687 0.05295008 0.52280813]]
3 4
[[0.3812449  0.02985151 0.0386507  0.5502529 ]]
3 5
[[0.37637532 0.02102848 0.02806372 0.57453245]]
3 6
[[0.36943874 0.01457884 0.02011159 0.59587085]]
3 7
[[0.36091527 0.01007897 0.01435049 0.6146552 ]]
3 8
[[0.35147023 0.00684249 0.01009139 0.6315959 ]]
4 1
[[0.21106695 0.22023109 0.24422745 0.32447448]]
4 2
[[0.3668276  0.0589298  0.07683612 0.49740642]]
4 3
[[0.38613534 0.03212968 0.0419463  0.5397887 ]]
4 4
[[0.38312212 0.02186615 0.02954937 0.5654624 ]]
4 5
[[0.37681556 0.01524156 0.02120652 0.5867364 ]]
4 6
[[0.36817598 0.01071465 0.01529135 0.60581803]]
4 7
[[0.35814264 0.00737951 0.01089809 0.62357974]]
4 8
[[0.34776828 0.00505226 0.00771328 0.63946617]]
5 1
[[0.1980187  0.22717217 0.25201532 0.32279387]]
5 2
[[0.29458526 0.08991937 0.12625627 0.48923904]]
5 3
[[0.39082098 0.02616386 0.03593204 0.5470831 ]]
5 4
[[0.38249695 0.01648139 0.02305947 0.57796216]]
5 5
[[0.3750

4 3
[[0.34668127 0.0187019  0.02644126 0.6081756 ]]
4 4
[[0.32661346 0.01185082 0.01751135 0.64402443]]
4 5
[[0.30475983 0.00748251 0.01150223 0.67625546]]
4 6
[[0.28273657 0.00476295 0.00761867 0.7048818 ]]
4 7
[[0.26146275 0.00297864 0.00497031 0.7305883 ]]
4 8
[[0.24057429 0.00185187 0.00322076 0.75435305]]
5 1
[[0.24590237 0.14883578 0.20445026 0.40081155]]
5 2
[[0.377263   0.02797718 0.04244683 0.55231297]]
5 3
[[0.3490327  0.01336925 0.01994335 0.61765474]]
5 4
[[0.3227733  0.00814306 0.01258799 0.6564956 ]]
5 5
[[0.30062357 0.00511221 0.00826282 0.6860014 ]]
5 6
[[0.27806085 0.00318638 0.00536476 0.713388  ]]
5 7
[[0.2554551  0.00201396 0.00351969 0.7390112 ]]
5 8
[[0.23501772 0.00126162 0.00230095 0.7614197 ]]
6 1
[[0.21291292 0.18087745 0.2357533  0.37045634]]
6 2
[[0.3479001  0.03223037 0.05419565 0.5656739 ]]
6 3
[[0.35615104 0.01007349 0.01634063 0.61743486]]
6 4
[[0.32029158 0.00568097 0.00920315 0.66482437]]
6 5
[[0.29512954 0.00349462 0.00590294 0.69547284]]
6 6
[[0.2730

5 4
[[0.39119852 0.00812433 0.01428338 0.5863938 ]]
5 5
[[0.37562895 0.00503829 0.00934628 0.60998654]]
5 6
[[0.35830143 0.00314958 0.00614087 0.63240814]]
5 7
[[0.33943704 0.00199413 0.00409323 0.6544756 ]]
5 8
[[0.3209037  0.00124204 0.00269601 0.67515826]]
6 1
[[0.17142008 0.23115823 0.24537772 0.35204396]]
6 2
[[0.24483682 0.08468357 0.14310104 0.52737856]]
6 3
[[0.42416376 0.01216222 0.02340412 0.5402699 ]]
6 4
[[0.39924332 0.00586723 0.01116994 0.5837195 ]]
6 5
[[0.37644675 0.00350024 0.00690872 0.6131443 ]]
6 6
[[0.3595797  0.0021652  0.00450989 0.63374525]]
6 7
[[0.3416953  0.00134159 0.00294265 0.6540205 ]]
6 8
[[0.3225938  0.00084524 0.00194805 0.67461294]]
7 1
[[0.16181423 0.23272534 0.2453156  0.3601448 ]]
7 2
[[0.19016182 0.13361539 0.19537365 0.48084912]]
7 3
[[0.37353987 0.0169775  0.03478798 0.57469463]]
7 4
[[0.41260862 0.00453741 0.00968564 0.5731683 ]]
7 5
[[0.3804815  0.00250321 0.00529245 0.6117228 ]]
7 6
[[0.35937548 0.00149591 0.00331582 0.6358128 ]]
7 7
[[0.3423

6 5
[[0.29849157 0.00208146 0.00419953 0.6952274 ]]
6 6
[[0.27283096 0.00118486 0.00252956 0.7234546 ]]
6 7
[[2.4758333e-01 6.6898990e-04 1.5194786e-03 7.5022817e-01]]
6 8
[[2.2330201e-01 3.8794734e-04 9.3822001e-04 7.7537179e-01]]
7 1
[[0.14640695 0.2434689  0.26189077 0.34823337]]
7 2
[[0.16579996 0.14722642 0.21647236 0.47050124]]
7 3
[[0.34727228 0.01177783 0.02340373 0.6175462 ]]
7 4
[[0.34780046 0.00287433 0.00616992 0.6431553 ]]
7 5
[[0.3010568  0.0014539  0.00315009 0.69433916]]
7 6
[[0.26956558 0.00079792 0.00181548 0.727821  ]]
7 7
[[2.4534911e-01 4.5294588e-04 1.0911063e-03 7.5310683e-01]]
7 8
[[2.2181460e-01 2.5451634e-04 6.5167493e-04 7.7727920e-01]]
8 1
[[0.13638228 0.24444507 0.2623158  0.3568568 ]]
8 2
[[0.13506033 0.19742824 0.25361097 0.41390043]]
8 3
[[0.26732647 0.02320193 0.04918818 0.6602834 ]]
8 4
[[0.3580641  0.0025348  0.00593881 0.6334623 ]]
8 5
[[0.3111206  0.00105842 0.00252241 0.6852986 ]]
8 6
[[2.7046624e-01 5.5257120e-04 1.3479758e-03 7.2763318e-01]]
8 7


7 6
[[0.33751124 0.00091827 0.00284608 0.65872437]]
7 7
[[3.1025437e-01 5.1497470e-04 1.7436966e-03 6.8748701e-01]]
7 8
[[2.8449345e-01 2.8789154e-04 1.0696480e-03 7.1414906e-01]]
8 1
[[0.13483143 0.23899752 0.299076   0.3270951 ]]
8 2
[[0.13323341 0.20762153 0.3155056  0.34363943]]
8 3
[[0.28678077 0.03991856 0.10790821 0.56539243]]
8 4
[[0.43525636 0.00340076 0.01063289 0.55070996]]
8 5
[[0.3918045  0.00130303 0.00420525 0.60268724]]
8 6
[[0.34909314 0.00066216 0.00224438 0.64800036]]
8 7
[[3.1512037e-01 3.5967442e-04 1.3154694e-03 6.8320447e-01]]
8 8
[[2.8917581e-01 2.0102263e-04 8.0416218e-04 7.0981896e-01]]
这是第1040局游戏，我死了
最后20盘的胜率为0.65
这是第1041局游戏，我赢了
最后20盘的胜率为0.65
这是第1042局游戏，我死了
最后20盘的胜率为0.7
这是第1043局游戏，我死了
最后20盘的胜率为0.7
这是第1044局游戏，我死了
最后20盘的胜率为0.65
这是第1045局游戏，我死了
最后20盘的胜率为0.65
这是第1046局游戏，我赢了
最后20盘的胜率为0.6
这是第1047局游戏，我死了
最后20盘的胜率为0.6
这是第1048局游戏，我赢了
最后20盘的胜率为0.55
这是第1049局游戏，我赢了
最后20盘的胜率为0.55
这是第1050局游戏，我赢了
最后20盘的胜率为0.55
这是第1051局游戏，我赢了
最后20盘的胜率为0.55
这是第1052局游戏，我死了
最后20盘的胜率为0.55
这是第1053

8 4
[[0.41202965 0.00307012 0.01197735 0.5729228 ]]
8 5
[[0.38412437 0.00108619 0.00421244 0.61057705]]
8 6
[[3.2734308e-01 5.3363707e-04 2.1451865e-03 6.6997814e-01]]
8 7
[[2.8328022e-01 2.7942428e-04 1.2120447e-03 7.1522826e-01]]
8 8
[[2.4639298e-01 1.4639631e-04 6.9433148e-04 7.5276631e-01]]
这是第1080局游戏，我死了
最后20盘的胜率为0.65
这是第1081局游戏，我死了
最后20盘的胜率为0.6
这是第1082局游戏，我赢了
最后20盘的胜率为0.55
这是第1083局游戏，我赢了
最后20盘的胜率为0.6
这是第1084局游戏，我赢了
最后20盘的胜率为0.65
这是第1085局游戏，我赢了
最后20盘的胜率为0.65
这是第1086局游戏，我赢了
最后20盘的胜率为0.7
这是第1087局游戏，我赢了
最后20盘的胜率为0.7
这是第1088局游戏，我赢了
最后20盘的胜率为0.7
这是第1089局游戏，我赢了
最后20盘的胜率为0.7
这是第1090局游戏，我死了
最后20盘的胜率为0.7
这是第1091局游戏，我赢了
最后20盘的胜率为0.7
这是第1092局游戏，我赢了
最后20盘的胜率为0.7
这是第1093局游戏，我赢了
最后20盘的胜率为0.75
这是第1094局游戏，我赢了
最后20盘的胜率为0.8
这是第1095局游戏，我赢了
最后20盘的胜率为0.85
这是第1096局游戏，我赢了
最后20盘的胜率为0.85
这是第1097局游戏，我死了
最后20盘的胜率为0.85
这是第1098局游戏，我赢了
最后20盘的胜率为0.8
这是第1099局游戏，我赢了
最后20盘的胜率为0.8
1 1
[[0.36303672 0.08352567 0.11471696 0.43872067]]
1 2
[[0.3687834  0.04625936 0.07164831 0.5133089 ]]
1 3
[[0.3647276  0.02443676 0.04

8 4
[[5.6511503e-01 3.8734585e-04 2.3198002e-03 4.3217778e-01]]
8 5
[[5.6715441e-01 1.5401658e-04 9.5537229e-04 4.3173623e-01]]
8 6
[[5.5429322e-01 6.9275615e-05 4.7789369e-04 4.4515961e-01]]
8 7
[[5.3695667e-01 3.2551114e-05 2.5420907e-04 4.6275648e-01]]
8 8
[[5.1650208e-01 1.5279438e-05 1.3507926e-04 4.8334756e-01]]
这是第1120局游戏，我赢了
最后20盘的胜率为0.4
这是第1121局游戏，我死了
最后20盘的胜率为0.4
这是第1122局游戏，我赢了
最后20盘的胜率为0.35
这是第1123局游戏，我赢了
最后20盘的胜率为0.35
这是第1124局游戏，我赢了
最后20盘的胜率为0.35
这是第1125局游戏，我赢了
最后20盘的胜率为0.35
这是第1126局游戏，我赢了
最后20盘的胜率为0.35
这是第1127局游戏，我赢了
最后20盘的胜率为0.4
这是第1128局游戏，我死了
最后20盘的胜率为0.45
这是第1129局游戏，我死了
最后20盘的胜率为0.4
这是第1130局游戏，我赢了
最后20盘的胜率为0.4
这是第1131局游戏，我死了
最后20盘的胜率为0.45
这是第1132局游戏，我赢了
最后20盘的胜率为0.4
这是第1133局游戏，我赢了
最后20盘的胜率为0.45
这是第1134局游戏，我死了
最后20盘的胜率为0.5
这是第1135局游戏，我死了
最后20盘的胜率为0.5
这是第1136局游戏，我死了
最后20盘的胜率为0.5
这是第1137局游戏，我死了
最后20盘的胜率为0.5
这是第1138局游戏，我赢了
最后20盘的胜率为0.5
这是第1139局游戏，我赢了
最后20盘的胜率为0.55
1 1
[[0.39817023 0.07924111 0.10808152 0.4145072 ]]
1 2
[[0.42269802 0.04266691 0.0650475  0.46958762]]
1 3
[[0

8 4
[[0.3944009  0.00074168 0.00438469 0.60047275]]
8 5
[[4.5498940e-01 1.9412144e-04 1.1466348e-03 5.4366988e-01]]
8 6
[[4.3006596e-01 8.4825442e-05 5.2257726e-04 5.6932664e-01]]
8 7
[[3.9076036e-01 3.8333517e-05 2.6087070e-04 6.0894036e-01]]
8 8
[[3.5273039e-01 1.7612063e-05 1.3477539e-04 6.4711726e-01]]
这是第1160局游戏，我赢了
最后20盘的胜率为0.6
这是第1161局游戏，我赢了
最后20盘的胜率为0.6
这是第1162局游戏，我死了
最后20盘的胜率为0.6
这是第1163局游戏，我赢了
最后20盘的胜率为0.55
这是第1164局游戏，我赢了
最后20盘的胜率为0.6
这是第1165局游戏，我死了
最后20盘的胜率为0.65
这是第1166局游戏，我死了
最后20盘的胜率为0.65
这是第1167局游戏，我死了
最后20盘的胜率为0.6
这是第1168局游戏，我赢了
最后20盘的胜率为0.55
这是第1169局游戏，我赢了
最后20盘的胜率为0.6
这是第1170局游戏，我赢了
最后20盘的胜率为0.65
这是第1171局游戏，我赢了
最后20盘的胜率为0.7
这是第1172局游戏，我死了
最后20盘的胜率为0.7
这是第1173局游戏，我死了
最后20盘的胜率为0.7
这是第1174局游戏，我死了
最后20盘的胜率为0.65
这是第1175局游戏，我死了
最后20盘的胜率为0.65
这是第1176局游戏，我死了
最后20盘的胜率为0.6
这是第1177局游戏，我赢了
最后20盘的胜率为0.55
这是第1178局游戏，我死了
最后20盘的胜率为0.55
这是第1179局游戏，我死了
最后20盘的胜率为0.5
1 1
[[0.40015793 0.06619653 0.09864485 0.43500063]]
1 2
[[0.41024813 0.03249329 0.05569227 0.50156635]]
1 3
[[0.41077894 0.

8 1
[[0.07544062 0.11940994 0.35866937 0.44648004]]
8 2
[[0.13408835 0.04100737 0.25066265 0.57424164]]
8 3
[[0.42602777 0.00144522 0.01120783 0.56131923]]
8 4
[[6.4588636e-01 1.2274548e-04 9.9520269e-04 3.5299569e-01]]
8 5
[[6.6938913e-01 4.2283595e-05 3.5715479e-04 3.3021143e-01]]
8 6
[[6.6776437e-01 1.6990380e-05 1.6069187e-04 3.3205795e-01]]
8 7
[[6.5732837e-01 6.9523599e-06 7.5908589e-05 3.4258878e-01]]
8 8
[[6.4609271e-01 2.8631264e-06 3.6551577e-05 3.5386789e-01]]
这是第1200局游戏，我死了
最后20盘的胜率为0.3
这是第1201局游戏，我死了
最后20盘的胜率为0.25
这是第1202局游戏，我死了
最后20盘的胜率为0.2
这是第1203局游戏，我死了
最后20盘的胜率为0.2
这是第1204局游戏，我死了
最后20盘的胜率为0.2
这是第1205局游戏，我赢了
最后20盘的胜率为0.2
这是第1206局游戏，我赢了
最后20盘的胜率为0.2
这是第1207局游戏，我死了
最后20盘的胜率为0.2
这是第1208局游戏，我死了
最后20盘的胜率为0.2
这是第1209局游戏，我死了
最后20盘的胜率为0.2
这是第1210局游戏，我赢了
最后20盘的胜率为0.2
这是第1211局游戏，我死了
最后20盘的胜率为0.2
这是第1212局游戏，我赢了
最后20盘的胜率为0.15
这是第1213局游戏，我赢了
最后20盘的胜率为0.2
这是第1214局游戏，我死了
最后20盘的胜率为0.25
这是第1215局游戏，我死了
最后20盘的胜率为0.25
这是第1216局游戏，我赢了
最后20盘的胜率为0.25
这是第1217局游戏，我赢了
最后20盘的胜率为0.3
这是第1218局游戏，我赢了


7 6
[[3.1825703e-01 5.5430457e-05 2.5174336e-04 6.8143582e-01]]
7 7
[[2.6939577e-01 2.3255223e-05 1.1592236e-04 7.3046511e-01]]
7 8
[[2.2787817e-01 9.9752415e-06 5.4366941e-05 7.7205747e-01]]
8 1
[[0.0799324  0.16139497 0.32163072 0.43704188]]
8 2
[[0.0951358  0.08316097 0.322563   0.49914026]]
8 3
[[0.41503352 0.0020933  0.01064123 0.57223195]]
8 4
[[4.8418614e-01 2.4237824e-04 1.1904725e-03 5.1438105e-01]]
8 5
[[4.1218469e-01 8.3283747e-05 4.1271147e-04 5.8731931e-01]]
8 6
[[3.4629709e-01 3.4005883e-05 1.7753642e-04 6.5349144e-01]]
8 7
[[2.9056641e-01 1.4154113e-05 7.9835372e-05 7.0933962e-01]]
8 8
[[2.4486959e-01 5.8967175e-06 3.6434711e-05 7.5508809e-01]]
这是第1240局游戏，我赢了
最后20盘的胜率为0.85
这是第1241局游戏，我赢了
最后20盘的胜率为0.9
这是第1242局游戏，我死了
最后20盘的胜率为0.9
这是第1243局游戏，我死了
最后20盘的胜率为0.85
这是第1244局游戏，我赢了
最后20盘的胜率为0.8
这是第1245局游戏，我赢了
最后20盘的胜率为0.85
这是第1246局游戏，我死了
最后20盘的胜率为0.85
这是第1247局游戏，我赢了
最后20盘的胜率为0.8
这是第1248局游戏，我赢了
最后20盘的胜率为0.8
这是第1249局游戏，我死了
最后20盘的胜率为0.8
这是第1250局游戏，我赢了
最后20盘的胜率为0.75
这是第1251局游戏，我死了
最后20

7 6
[[3.4698036e-01 4.0440285e-05 1.9740088e-04 6.5278184e-01]]
7 7
[[2.9059908e-01 1.6513270e-05 8.8533809e-05 7.0929593e-01]]
7 8
[[2.3930632e-01 6.9176131e-06 4.0511775e-05 7.6064628e-01]]
8 1
[[0.07617866 0.15666963 0.3360551  0.43109664]]
8 2
[[0.10938518 0.06454616 0.3158641  0.5102045 ]]
8 3
[[0.51995367 0.00118397 0.00623148 0.47263092]]
8 4
[[5.3479201e-01 1.7653462e-04 9.2828472e-04 4.6410322e-01]]
8 5
[[4.5853949e-01 5.9920396e-05 3.2188630e-04 5.4107869e-01]]
8 6
[[3.8465691e-01 2.4377030e-05 1.3788893e-04 6.1518079e-01]]
8 7
[[3.2084325e-01 9.9275267e-06 6.0588693e-05 6.7908627e-01]]
8 8
[[2.6738679e-01 4.0072555e-06 2.6945896e-05 7.3258215e-01]]
这是第1280局游戏，我赢了
最后20盘的胜率为0.5
这是第1281局游戏，我死了
最后20盘的胜率为0.55
这是第1282局游戏，我死了
最后20盘的胜率为0.55
这是第1283局游戏，我死了
最后20盘的胜率为0.55
这是第1284局游戏，我赢了
最后20盘的胜率为0.5
这是第1285局游戏，我赢了
最后20盘的胜率为0.5
这是第1286局游戏，我死了
最后20盘的胜率为0.5
这是第1287局游戏，我赢了
最后20盘的胜率为0.5
这是第1288局游戏，我死了
最后20盘的胜率为0.55
这是第1289局游戏，我赢了
最后20盘的胜率为0.5
这是第1290局游戏，我死了
最后20盘的胜率为0.55
这是第1291局游戏，我死了
最后20

7 6
[[5.3841162e-01 5.7777837e-05 3.8248140e-04 4.6114811e-01]]
7 7
[[4.7889823e-01 2.5946902e-05 1.8990567e-04 5.2088594e-01]]
7 8
[[4.1903964e-01 1.2025303e-05 9.6948672e-05 5.8085144e-01]]
8 1
[[0.05984412 0.16413307 0.3423618  0.43366098]]
8 2
[[0.05535164 0.1077802  0.36159304 0.47527513]]
8 3
[[0.2619094  0.01162117 0.09240839 0.63406104]]
8 4
[[6.7124158e-01 2.6280241e-04 1.9950378e-03 3.2650062e-01]]
8 5
[[6.6328818e-01 8.1793369e-05 6.2422769e-04 3.3600587e-01]]
8 6
[[6.0030639e-01 3.4204582e-05 2.7370232e-04 3.9938578e-01]]
8 7
[[5.3680617e-01 1.5152116e-05 1.3075383e-04 4.6304792e-01]]
8 8
[[4.7748074e-01 6.7923766e-06 6.5000466e-05 5.2244747e-01]]
这是第1320局游戏，我死了
最后20盘的胜率为0.6
这是第1321局游戏，我赢了
最后20盘的胜率为0.55
这是第1322局游戏，我赢了
最后20盘的胜率为0.55
这是第1323局游戏，我赢了
最后20盘的胜率为0.55
这是第1324局游戏，我赢了
最后20盘的胜率为0.55
这是第1325局游戏，我赢了
最后20盘的胜率为0.55
这是第1326局游戏，我死了
最后20盘的胜率为0.55
这是第1327局游戏，我赢了
最后20盘的胜率为0.5
这是第1328局游戏，我赢了
最后20盘的胜率为0.5
这是第1329局游戏，我死了
最后20盘的胜率为0.55
这是第1330局游戏，我死了
最后20盘的胜率为0.5
这是第1331局游戏，我死了
最后

8 4
[[0.03710569 0.04343188 0.42326936 0.496193  ]]
8 5
[[0.14135517 0.0099025  0.24864858 0.6000938 ]]
8 6
[[0.5577596  0.00060646 0.01673096 0.42490295]]
8 7
[[7.1854985e-01 9.9102850e-05 2.4419185e-03 2.7890918e-01]]
8 8
[[7.2937548e-01 4.1555981e-05 1.0376129e-03 2.6954535e-01]]
这是第1360局游戏，我死了
最后20盘的胜率为0.1
这是第1361局游戏，我死了
最后20盘的胜率为0.1
这是第1362局游戏，我死了
最后20盘的胜率为0.1
这是第1363局游戏，我死了
最后20盘的胜率为0.1
这是第1364局游戏，我死了
最后20盘的胜率为0.05
这是第1365局游戏，我死了
最后20盘的胜率为0.05
这是第1366局游戏，我死了
最后20盘的胜率为0.0
这是第1367局游戏，我死了
最后20盘的胜率为0.0
这是第1368局游戏，我死了
最后20盘的胜率为0.0
这是第1369局游戏，我死了
最后20盘的胜率为0.0
这是第1370局游戏，我死了
最后20盘的胜率为0.0
这是第1371局游戏，我死了
最后20盘的胜率为0.0
这是第1372局游戏，我死了
最后20盘的胜率为0.0
这是第1373局游戏，我赢了
最后20盘的胜率为0.0
这是第1374局游戏，我死了
最后20盘的胜率为0.05
这是第1375局游戏，我死了
最后20盘的胜率为0.05
这是第1376局游戏，我死了
最后20盘的胜率为0.05
这是第1377局游戏，我死了
最后20盘的胜率为0.05
这是第1378局游戏，我赢了
最后20盘的胜率为0.05
这是第1379局游戏，我死了
最后20盘的胜率为0.1
1 1
[[0.41041738 0.08073466 0.14630061 0.3625473 ]]
1 2
[[0.43949047 0.0465595  0.09650926 0.41744077]]
1 3
[[0.4622109  0.02543774 0.06427982 0.4480

这是第1400局游戏，我死了
最后20盘的胜率为0.05
这是第1401局游戏，我死了
最后20盘的胜率为0.05
这是第1402局游戏，我死了
最后20盘的胜率为0.05
这是第1403局游戏，我死了
最后20盘的胜率为0.05
这是第1404局游戏，我死了
最后20盘的胜率为0.05
这是第1405局游戏，我死了
最后20盘的胜率为0.05
这是第1406局游戏，我死了
最后20盘的胜率为0.05
这是第1407局游戏，我死了
最后20盘的胜率为0.05
这是第1408局游戏，我死了
最后20盘的胜率为0.05
这是第1409局游戏，我死了
最后20盘的胜率为0.0
这是第1410局游戏，我死了
最后20盘的胜率为0.0
这是第1411局游戏，我赢了
最后20盘的胜率为0.0
这是第1412局游戏，我赢了
最后20盘的胜率为0.05
这是第1413局游戏，我死了
最后20盘的胜率为0.1
这是第1414局游戏，我死了
最后20盘的胜率为0.1
这是第1415局游戏，我死了
最后20盘的胜率为0.1
这是第1416局游戏，我死了
最后20盘的胜率为0.1
这是第1417局游戏，我死了
最后20盘的胜率为0.1
这是第1418局游戏，我赢了
最后20盘的胜率为0.1
这是第1419局游戏，我死了
最后20盘的胜率为0.15
1 1
[[0.4256752  0.07275882 0.1361304  0.36543557]]
1 2
[[0.46536127 0.03886024 0.0848221  0.41095644]]
1 3
[[0.4941097  0.0196206  0.05321063 0.4330591 ]]
1 4
[[0.5154279  0.00963852 0.03276655 0.4421671 ]]
1 5
[[0.53063303 0.00463869 0.01981748 0.44491073]]
1 6
[[0.541474   0.00222776 0.01194844 0.44434983]]
1 7
[[0.5504377  0.00106564 0.0071806  0.4413161 ]]
1 8
[[5.5793697e-01 5.0934189e-04 4.3097292e-03 4.3724400e-01]]
2

这是第1440局游戏，我赢了
最后20盘的胜率为0.15
这是第1441局游戏，我赢了
最后20盘的胜率为0.15
这是第1442局游戏，我死了
最后20盘的胜率为0.2
这是第1443局游戏，我死了
最后20盘的胜率为0.2
这是第1444局游戏，我死了
最后20盘的胜率为0.2
这是第1445局游戏，我死了
最后20盘的胜率为0.2
这是第1446局游戏，我死了
最后20盘的胜率为0.2
这是第1447局游戏，我赢了
最后20盘的胜率为0.2
这是第1448局游戏，我死了
最后20盘的胜率为0.25
这是第1449局游戏，我死了
最后20盘的胜率为0.25
这是第1450局游戏，我死了
最后20盘的胜率为0.25
这是第1451局游戏，我死了
最后20盘的胜率为0.25
这是第1452局游戏，我死了
最后20盘的胜率为0.25
这是第1453局游戏，我死了
最后20盘的胜率为0.2
这是第1454局游戏，我死了
最后20盘的胜率为0.2
这是第1455局游戏，我死了
最后20盘的胜率为0.2
这是第1456局游戏，我赢了
最后20盘的胜率为0.2
这是第1457局游戏，我赢了
最后20盘的胜率为0.25
这是第1458局游戏，我赢了
最后20盘的胜率为0.25
这是第1459局游戏，我死了
最后20盘的胜率为0.3
1 1
[[0.4359594  0.06691343 0.13319045 0.36393672]]
1 2
[[0.4925704  0.03452722 0.0807742  0.3921282 ]]
1 3
[[0.5295673  0.016971   0.05017461 0.4032871 ]]
1 4
[[0.5592683  0.0080841  0.03059093 0.4020567 ]]
1 5
[[0.5830927  0.00377562 0.01834563 0.394786  ]]
1 6
[[0.60285336 0.00175037 0.01090741 0.38448882]]
1 7
[[0.61997986 0.00081008 0.00646612 0.37274387]]
1 8
[[6.3569486e-01 3.7363995e-04 3.8205946e-03 3.6011082e-01]]
2 1

这是第1480局游戏，我赢了
最后20盘的胜率为0.2
这是第1481局游戏，我赢了
最后20盘的胜率为0.25
这是第1482局游戏，我赢了
最后20盘的胜率为0.25
这是第1483局游戏，我赢了
最后20盘的胜率为0.3
这是第1484局游戏，我死了
最后20盘的胜率为0.3
这是第1485局游戏，我死了
最后20盘的胜率为0.3
这是第1486局游戏，我死了
最后20盘的胜率为0.3
这是第1487局游戏，我死了
最后20盘的胜率为0.3
这是第1488局游戏，我赢了
最后20盘的胜率为0.3
这是第1489局游戏，我赢了
最后20盘的胜率为0.35
这是第1490局游戏，我赢了
最后20盘的胜率为0.4
这是第1491局游戏，我死了
最后20盘的胜率为0.45
这是第1492局游戏，我死了
最后20盘的胜率为0.4
这是第1493局游戏，我死了
最后20盘的胜率为0.4
这是第1494局游戏，我死了
最后20盘的胜率为0.4
这是第1495局游戏，我赢了
最后20盘的胜率为0.4
这是第1496局游戏，我死了
最后20盘的胜率为0.45
这是第1497局游戏，我死了
最后20盘的胜率为0.4
这是第1498局游戏，我赢了
最后20盘的胜率为0.4
这是第1499局游戏，我赢了
最后20盘的胜率为0.45
1 1
[[0.47197372 0.06359128 0.12438583 0.3400492 ]]
1 2
[[0.5364132  0.03173185 0.07581478 0.35604018]]
1 3
[[0.58880985 0.01485895 0.04568899 0.35064226]]
1 4
[[0.6322897  0.00669714 0.02676859 0.33424455]]
1 5
[[0.6687841  0.00296319 0.0154092  0.31284347]]
1 6
[[0.69988364 0.0013028  0.00880438 0.29000914]]
1 7
[[7.2715837e-01 5.7082251e-04 5.0048162e-03 2.6726598e-01]]
1 8
[[7.5195336e-01 2.4840445e-04 2.8305927e-03 2.4496771e

这是第1520局游戏，我死了
最后20盘的胜率为0.25
这是第1521局游戏，我死了
最后20盘的胜率为0.25
这是第1522局游戏，我死了
最后20盘的胜率为0.25
这是第1523局游戏，我死了
最后20盘的胜率为0.25
这是第1524局游戏，我死了
最后20盘的胜率为0.25
这是第1525局游戏，我死了
最后20盘的胜率为0.2
这是第1526局游戏，我赢了
最后20盘的胜率为0.2
这是第1527局游戏，我赢了
最后20盘的胜率为0.25
这是第1528局游戏，我死了
最后20盘的胜率为0.25
这是第1529局游戏，我死了
最后20盘的胜率为0.2
这是第1530局游戏，我死了
最后20盘的胜率为0.2
这是第1531局游戏，我死了
最后20盘的胜率为0.2
这是第1532局游戏，我死了
最后20盘的胜率为0.2
这是第1533局游戏，我死了
最后20盘的胜率为0.2
这是第1534局游戏，我死了
最后20盘的胜率为0.2
这是第1535局游戏，我死了
最后20盘的胜率为0.15
这是第1536局游戏，我赢了
最后20盘的胜率为0.15
这是第1537局游戏，我死了
最后20盘的胜率为0.2
这是第1538局游戏，我赢了
最后20盘的胜率为0.2
这是第1539局游戏，我赢了
最后20盘的胜率为0.2
1 1
[[0.45865104 0.06476032 0.12842564 0.34816307]]
1 2
[[0.50904036 0.0339565  0.081297   0.37570617]]
1 3
[[0.5510325  0.01675878 0.0510242  0.38118452]]
1 4
[[0.5860911  0.0079619  0.03121714 0.37472984]]
1 5
[[0.61480814 0.00370743 0.0187533  0.36273122]]
1 6
[[0.63871306 0.00172685 0.01124216 0.3483179 ]]
1 7
[[0.65998846 0.00079876 0.00669593 0.33251685]]
1 8
[[6.7939466e-01 3.6884216e-04 3.9830571e-03 3.1625348e-01]]
2 1

8 7
[[8.5346401e-01 1.7258664e-05 5.8574259e-04 1.4593300e-01]]
8 8
[[8.5358202e-01 8.3087289e-06 3.2167273e-04 1.4608791e-01]]
这是第1560局游戏，我死了
最后20盘的胜率为0.45
这是第1561局游戏，我死了
最后20盘的胜率为0.4
这是第1562局游戏，我死了
最后20盘的胜率为0.35
这是第1563局游戏，我赢了
最后20盘的胜率为0.3
这是第1564局游戏，我死了
最后20盘的胜率为0.3
这是第1565局游戏，我赢了
最后20盘的胜率为0.3
这是第1566局游戏，我死了
最后20盘的胜率为0.35
这是第1567局游戏，我死了
最后20盘的胜率为0.35
这是第1568局游戏，我赢了
最后20盘的胜率为0.35
这是第1569局游戏，我赢了
最后20盘的胜率为0.35
这是第1570局游戏，我死了
最后20盘的胜率为0.4
这是第1571局游戏，我死了
最后20盘的胜率为0.35
这是第1572局游戏，我死了
最后20盘的胜率为0.35
这是第1573局游戏，我赢了
最后20盘的胜率为0.35
这是第1574局游戏，我死了
最后20盘的胜率为0.4
这是第1575局游戏，我死了
最后20盘的胜率为0.35
这是第1576局游戏，我赢了
最后20盘的胜率为0.35
这是第1577局游戏，我死了
最后20盘的胜率为0.35
这是第1578局游戏，我赢了
最后20盘的胜率为0.35
这是第1579局游戏，我死了
最后20盘的胜率为0.4
1 1
[[0.45643365 0.06098219 0.12093057 0.36165354]]
1 2
[[0.49547958 0.0316262  0.07621887 0.39667532]]
1 3
[[0.5317925  0.01537914 0.04735917 0.40546915]]
1 4
[[0.5615671  0.00708194 0.02825311 0.40309775]]
1 5
[[0.58477116 0.00320915 0.01660124 0.39541847]]
1 6
[[0.6038958  0.00146419 0.00978233 

8 4
[[0.30131203 0.00316725 0.07416788 0.6213528 ]]
8 5
[[6.5313721e-01 2.0586878e-04 7.4542854e-03 3.3920270e-01]]
8 6
[[7.6666433e-01 4.2723004e-05 1.6391738e-03 2.3165385e-01]]
8 7
[[7.8794330e-01 1.6161524e-05 6.8428449e-04 2.1135628e-01]]
8 8
[[7.7910477e-01 7.9653655e-06 3.8438290e-04 2.2050285e-01]]
这是第1600局游戏，我赢了
最后20盘的胜率为0.3
这是第1601局游戏，我死了
最后20盘的胜率为0.3
这是第1602局游戏，我赢了
最后20盘的胜率为0.3
这是第1603局游戏，我死了
最后20盘的胜率为0.35
这是第1604局游戏，我死了
最后20盘的胜率为0.35
这是第1605局游戏，我死了
最后20盘的胜率为0.35
这是第1606局游戏，我死了
最后20盘的胜率为0.3
这是第1607局游戏，我死了
最后20盘的胜率为0.3
这是第1608局游戏，我死了
最后20盘的胜率为0.3
这是第1609局游戏，我死了
最后20盘的胜率为0.3
这是第1610局游戏，我赢了
最后20盘的胜率为0.25
这是第1611局游戏，我赢了
最后20盘的胜率为0.3
这是第1612局游戏，我死了
最后20盘的胜率为0.35
这是第1613局游戏，我赢了
最后20盘的胜率为0.35
这是第1614局游戏，我死了
最后20盘的胜率为0.4
这是第1615局游戏，我死了
最后20盘的胜率为0.4
这是第1616局游戏，我死了
最后20盘的胜率为0.35
这是第1617局游戏，我赢了
最后20盘的胜率为0.3
这是第1618局游戏，我死了
最后20盘的胜率为0.35
这是第1619局游戏，我赢了
最后20盘的胜率为0.35
1 1
[[0.41508645 0.06249192 0.11986548 0.40255612]]
1 2
[[0.41878393 0.03392425 0.08000939 0.4672824 ]]
1 3
[[0.4262317  0.

8 4
[[5.2042264e-01 2.5525503e-04 7.1808766e-03 4.7214127e-01]]
8 5
[[6.0536635e-01 5.3808923e-05 1.5723832e-03 3.9300746e-01]]
8 6
[[5.4384488e-01 2.3137816e-05 6.8439764e-04 4.5544758e-01]]
8 7
[[4.7026989e-01 1.0880557e-05 3.5550524e-04 5.2936375e-01]]
8 8
[[4.0751624e-01 5.1525062e-06 2.0611177e-04 5.9227252e-01]]
这是第1640局游戏，我赢了
最后20盘的胜率为0.55
这是第1641局游戏，我赢了
最后20盘的胜率为0.6
这是第1642局游戏，我赢了
最后20盘的胜率为0.65
这是第1643局游戏，我赢了
最后20盘的胜率为0.65
这是第1644局游戏，我死了
最后20盘的胜率为0.65
这是第1645局游戏，我赢了
最后20盘的胜率为0.65
这是第1646局游戏，我死了
最后20盘的胜率为0.65
这是第1647局游戏，我赢了
最后20盘的胜率为0.6
这是第1648局游戏，我赢了
最后20盘的胜率为0.6
这是第1649局游戏，我赢了
最后20盘的胜率为0.6
这是第1650局游戏，我死了
最后20盘的胜率为0.65
这是第1651局游戏，我赢了
最后20盘的胜率为0.65
这是第1652局游戏，我死了
最后20盘的胜率为0.7
这是第1653局游戏，我赢了
最后20盘的胜率为0.7
这是第1654局游戏，我赢了
最后20盘的胜率为0.7
这是第1655局游戏，我死了
最后20盘的胜率为0.75
这是第1656局游戏，我赢了
最后20盘的胜率为0.75
这是第1657局游戏，我赢了
最后20盘的胜率为0.75
这是第1658局游戏，我赢了
最后20盘的胜率为0.75
这是第1659局游戏，我赢了
最后20盘的胜率为0.75
1 1
[[0.3595077  0.06560092 0.11410435 0.460787  ]]
1 2
[[0.33947825 0.03458712 0.07351814 0.5524165 ]]
1 3

8 4
[[5.7033402e-01 1.2551638e-04 2.2190027e-03 4.2732146e-01]]
8 5
[[4.6334389e-01 4.0594874e-05 7.4727915e-04 5.3586823e-01]]
8 6
[[3.4985885e-01 1.6640384e-05 3.3283720e-04 6.4979172e-01]]
8 7
[[2.5281146e-01 6.9542971e-06 1.5843795e-04 7.4702317e-01]]
8 8
[[1.7947082e-01 2.8623974e-06 7.6468634e-05 8.2044983e-01]]
这是第1680局游戏，我赢了
最后20盘的胜率为0.55
这是第1681局游戏，我赢了
最后20盘的胜率为0.55
这是第1682局游戏，我赢了
最后20盘的胜率为0.55
这是第1683局游戏，我死了
最后20盘的胜率为0.6
这是第1684局游戏，我赢了
最后20盘的胜率为0.6
这是第1685局游戏，我赢了
最后20盘的胜率为0.65
这是第1686局游戏，我赢了
最后20盘的胜率为0.65
这是第1687局游戏，我赢了
最后20盘的胜率为0.65
这是第1688局游戏，我赢了
最后20盘的胜率为0.65
这是第1689局游戏，我赢了
最后20盘的胜率为0.7
这是第1690局游戏，我赢了
最后20盘的胜率为0.75
这是第1691局游戏，我赢了
最后20盘的胜率为0.75
这是第1692局游戏，我赢了
最后20盘的胜率为0.75
这是第1693局游戏，我赢了
最后20盘的胜率为0.75
这是第1694局游戏，我死了
最后20盘的胜率为0.8
这是第1695局游戏，我赢了
最后20盘的胜率为0.8
这是第1696局游戏，我赢了
最后20盘的胜率为0.8
这是第1697局游戏，我死了
最后20盘的胜率为0.8
这是第1698局游戏，我赢了
最后20盘的胜率为0.75
这是第1699局游戏，我赢了
最后20盘的胜率为0.8
1 1
[[0.3774158  0.05486874 0.09723663 0.4704788 ]]
1 2
[[0.35784572 0.02600888 0.05680335 0.5593421 ]]
1 3


7 6
[[2.8481051e-01 1.9147128e-05 2.9619009e-04 7.1487409e-01]]
7 7
[[2.2309004e-01 7.2906696e-06 1.4141969e-04 7.7676129e-01]]
7 8
[[1.8306507e-01 2.8958991e-06 7.0942304e-05 8.1686109e-01]]
8 1
[[0.09626119 0.1485008  0.2881571  0.46708086]]
8 2
[[0.13916619 0.03375824 0.29082075 0.5362548 ]]
8 3
[[0.54687744 0.00063216 0.00863777 0.44385263]]
8 4
[[5.3798997e-01 8.3495572e-05 1.2913913e-03 4.6063516e-01]]
8 5
[[4.2847830e-01 2.7126907e-05 4.5965490e-04 5.7103491e-01]]
8 6
[[3.3334133e-01 1.0934041e-05 2.1180480e-04 6.6643596e-01]]
8 7
[[2.5156713e-01 4.2221945e-06 9.6634605e-05 7.4833208e-01]]
8 8
[[1.9620931e-01 1.5863022e-06 4.5745455e-05 8.0374342e-01]]
这是第1720局游戏，我赢了
最后20盘的胜率为0.65
这是第1721局游戏，我赢了
最后20盘的胜率为0.65
这是第1722局游戏，我赢了
最后20盘的胜率为0.65
这是第1723局游戏，我赢了
最后20盘的胜率为0.65
这是第1724局游戏，我赢了
最后20盘的胜率为0.65
这是第1725局游戏，我赢了
最后20盘的胜率为0.65
这是第1726局游戏，我赢了
最后20盘的胜率为0.65
这是第1727局游戏，我赢了
最后20盘的胜率为0.65
这是第1728局游戏，我死了
最后20盘的胜率为0.7
这是第1729局游戏，我赢了
最后20盘的胜率为0.65
这是第1730局游戏，我死了
最后20盘的胜率为0.7
这是第1731局游戏，我死了


6 8
[[4.0003124e-01 1.0510675e-05 2.1345528e-04 5.9974480e-01]]
7 1
[[0.10877812 0.25383723 0.25775814 0.37962648]]
7 2
[[0.14986596 0.08446956 0.3263464  0.43931812]]
7 3
[[0.63972944 0.00141738 0.01452511 0.34432805]]
7 4
[[6.8612486e-01 2.1348086e-04 2.6493494e-03 3.1101233e-01]]
7 5
[[6.2276828e-01 7.9470941e-05 1.1103533e-03 3.7604189e-01]]
7 6
[[5.645129e-01 3.144700e-05 5.286911e-04 4.349269e-01]]
7 7
[[5.0397873e-01 1.2847221e-05 2.6080137e-04 4.9574766e-01]]
7 8
[[4.4104654e-01 5.6769973e-06 1.3970594e-04 5.5880809e-01]]
8 1
[[0.09666517 0.25688797 0.25375298 0.39269385]]
8 2
[[0.11026658 0.13699695 0.31603155 0.43670496]]
8 3
[[0.5004117  0.00511448 0.05509978 0.43937403]]
8 4
[[7.1391022e-01 1.7756748e-04 2.8173819e-03 2.8309488e-01]]
8 5
[[6.8355918e-01 4.7587142e-05 8.6154521e-04 3.1553170e-01]]
8 6
[[6.2436616e-01 1.9129022e-05 3.9691114e-04 3.7521780e-01]]
8 7
[[5.6738448e-01 7.5546282e-06 1.8995475e-04 4.3241796e-01]]
8 8
[[5.0658154e-01 3.0822378e-06 9.3840907e-05 4.93

6 2
[[0.49238524 0.00598459 0.05154238 0.45008776]]
6 3
[[6.2247699e-01 4.0427255e-04 4.2562783e-03 3.7286243e-01]]
6 4
[[5.4911214e-01 1.3845312e-04 1.6451455e-03 4.4910425e-01]]
6 5
[[4.6637660e-01 5.5465800e-05 7.7617908e-04 5.3279173e-01]]
6 6
[[3.7751848e-01 2.2837166e-05 3.8342949e-04 6.2207526e-01]]
6 7
[[3.1260464e-01 9.5927498e-06 1.9774420e-04 6.8718803e-01]]
6 8
[[2.7129784e-01 3.9784063e-06 1.0357076e-04 7.2859466e-01]]
7 1
[[0.0805629  0.16622068 0.3271924  0.42602402]]
7 2
[[0.28007647 0.0170889  0.17641263 0.52642196]]
7 3
[[6.4571983e-01 3.2447206e-04 4.5067435e-03 3.4944895e-01]]
7 4
[[6.1284637e-01 7.5382683e-05 1.1900536e-03 3.8588822e-01]]
7 5
[[5.3580874e-01 2.9028248e-05 5.3234299e-04 4.6362990e-01]]
7 6
[[4.4925880e-01 1.1613633e-05 2.5128515e-04 5.5047834e-01]]
7 7
[[3.6144978e-01 4.7699814e-06 1.2384378e-04 6.3842165e-01]]
7 8
[[2.9521710e-01 2.0038738e-06 6.3691514e-05 7.0471722e-01]]
8 1
[[0.06703103 0.17676866 0.316984   0.43921632]]
8 2
[[0.12125113 0.03403

5 4
[[4.2748088e-01 3.5961845e-04 3.2033038e-03 5.6895620e-01]]
5 5
[[3.2978258e-01 1.7150055e-04 1.7853086e-03 6.6826063e-01]]
5 6
[[2.795362e-01 7.982954e-05 1.011315e-03 7.193727e-01]]
5 7
[[2.4181965e-01 3.6320740e-05 5.6836440e-04 7.5757575e-01]]
5 8
[[2.1142323e-01 1.6572038e-05 3.1850737e-04 7.8824168e-01]]
6 1
[[0.08205362 0.12436314 0.42649314 0.36709008]]
6 2
[[0.4448451  0.00744259 0.0869549  0.46075737]]
6 3
[[6.2160105e-01 4.4403764e-04 5.1483512e-03 3.7280655e-01]]
6 4
[[5.0698566e-01 1.7848310e-04 2.1470583e-03 4.9068877e-01]]
6 5
[[3.9723089e-01 8.2780964e-05 1.1209726e-03 6.0156530e-01]]
6 6
[[3.0356142e-01 3.8842303e-05 6.1913190e-04 6.9578058e-01]]
6 7
[[2.5436214e-01 1.7957182e-05 3.4789319e-04 7.4527198e-01]]
6 8
[[2.1795255e-01 8.2146889e-06 1.9602165e-04 7.8184325e-01]]
7 1
[[0.06401448 0.1388517  0.4198717  0.37726212]]
7 2
[[0.20813583 0.01964814 0.29816473 0.47405136]]
7 3
[[6.5397155e-01 3.4620173e-04 5.6997230e-03 3.3998254e-01]]
7 4
[[5.9075713e-01 9.032977

4 6
[[4.78458822e-01 1.02399455e-04 1.17307378e-03 5.20265698e-01]]
4 7
[[4.678228e-01 4.588450e-05 6.565572e-04 5.314747e-01]]
4 8
[[4.6251780e-01 1.9922332e-05 3.6089914e-04 5.3710139e-01]]
5 1
[[0.09284192 0.12816396 0.43122047 0.34777364]]
5 2
[[0.64783025 0.00272373 0.0232702  0.32617584]]
5 3
[[7.0054555e-01 4.6289875e-04 4.3434440e-03 2.9464811e-01]]
5 4
[[6.4964795e-01 1.9842612e-04 2.1213326e-03 3.4803224e-01]]
5 5
[[5.7923365e-01 9.3350063e-05 1.1564334e-03 4.1951656e-01]]
5 6
[[5.2360380e-01 4.5821787e-05 6.7290326e-04 4.7567749e-01]]
5 7
[[4.8682642e-01 2.1149797e-05 3.8062176e-04 5.1277179e-01]]
5 8
[[4.6864772e-01 9.6592794e-06 2.1486131e-04 5.3112775e-01]]
6 1
[[0.06823514 0.1594915  0.41910234 0.35317102]]
6 2
[[0.42966565 0.0092593  0.10987793 0.45119706]]
6 3
[[7.4422437e-01 2.6639004e-04 3.5340439e-03 2.5197521e-01]]
6 4
[[7.1837658e-01 9.2961454e-05 1.3538079e-03 2.8017658e-01]]
6 5
[[6.6747260e-01 3.9625415e-05 6.7323545e-04 3.3181453e-01]]
6 6
[[5.9647393e-01 1.90

3 8
[[3.1136760e-01 6.6314089e-05 5.4172339e-04 6.8802434e-01]]
4 1
[[0.10354803 0.23254888 0.29471382 0.36918926]]
4 2
[[0.59369224 0.00460708 0.01974685 0.38195387]]
4 3
[[0.5189678  0.00169509 0.00754559 0.47179154]]
4 4
[[0.42116466 0.00082227 0.00397185 0.57404125]]
4 5
[[3.6376020e-01 4.0714763e-04 2.2418452e-03 6.3359082e-01]]
4 6
[[3.3478636e-01 1.9058128e-04 1.2373157e-03 6.6378570e-01]]
4 7
[[3.1430447e-01 8.8617649e-05 6.8292575e-04 6.8492401e-01]]
4 8
[[2.9870015e-01 3.8530135e-05 3.5885992e-04 7.0090246e-01]]
5 1
[[0.08146077 0.26741585 0.2684863  0.38263705]]
5 2
[[0.5167476  0.00921565 0.04783192 0.42620486]]
5 3
[[0.6005297  0.00089008 0.00541343 0.39316684]]
5 4
[[5.0773197e-01 3.9393303e-04 2.4826075e-03 4.8939151e-01]]
5 5
[[4.0805137e-01 1.9215459e-04 1.3182532e-03 5.9043825e-01]]
5 6
[[3.4645063e-01 9.5279931e-05 7.4193906e-04 6.5271211e-01]]
5 7
[[3.1416175e-01 4.4379929e-05 4.0673712e-04 6.8538713e-01]]
5 8
[[2.9168582e-01 2.0751537e-05 2.2456290e-04 7.0806891e-0

3 8
[[2.3230457e-01 8.2271035e-05 6.6755532e-04 7.6694554e-01]]
4 1
[[0.11972672 0.20222922 0.3034583  0.37458578]]
4 2
[[0.5546882  0.00475652 0.01954152 0.4210137 ]]
4 3
[[0.45303532 0.00207667 0.00887857 0.53600943]]
4 4
[[0.34654582 0.00104087 0.00482151 0.64759177]]
4 5
[[2.9197073e-01 5.0749729e-04 2.7395864e-03 7.0478213e-01]]
4 6
[[2.6022437e-01 2.3911090e-04 1.5314097e-03 7.3800510e-01]]
4 7
[[2.3639669e-01 1.1109780e-04 8.4871933e-04 7.6264352e-01]]
4 8
[[2.1756969e-01 4.8120724e-05 4.4559792e-04 7.8193659e-01]]
5 1
[[0.09293006 0.25682706 0.27645642 0.37378645]]
5 2
[[0.56417316 0.00489706 0.02427417 0.40665564]]
5 3
[[0.53258455 0.00108224 0.00614255 0.46019065]]
5 4
[[4.2344770e-01 5.1452656e-04 3.0763485e-03 5.7296145e-01]]
5 5
[[3.1896046e-01 2.5664587e-04 1.6741415e-03 6.7910874e-01]]
5 6
[[2.6357168e-01 1.2487703e-04 9.4547571e-04 7.3535800e-01]]
5 7
[[2.3003693e-01 5.7911435e-05 5.1965343e-04 7.6938546e-01]]
5 8
[[2.0681812e-01 2.7316240e-05 2.9127626e-04 7.9286331e-0

3 4
[[0.45338783 0.00124067 0.00468223 0.5406893 ]]
3 5
[[4.4006425e-01 5.5163715e-04 2.4996453e-03 5.5688447e-01]]
3 6
[[4.3647259e-01 2.3163397e-04 1.2699717e-03 5.6202579e-01]]
3 7
[[4.3324706e-01 9.5111114e-05 6.3201785e-04 5.6602573e-01]]
3 8
[[4.2975664e-01 3.8947081e-05 3.1445350e-04 5.6988996e-01]]
4 1
[[0.53963697 0.02469829 0.06580582 0.3698589 ]]
4 2
[[0.6320174  0.00294446 0.01137637 0.3536618 ]]
4 3
[[0.5676591  0.00126762 0.00533603 0.4257373 ]]
4 4
[[0.49959573 0.00058349 0.00268909 0.49713168]]
4 5
[[4.5268539e-01 2.7246066e-04 1.4328471e-03 5.4560930e-01]]
4 6
[[4.3299559e-01 1.2242229e-04 7.6994853e-04 5.6611204e-01]]
4 7
[[4.2294028e-01 5.3131600e-05 4.0263939e-04 5.7660395e-01]]
4 8
[[4.1944087e-01 2.2027232e-05 2.0228105e-04 5.8033484e-01]]
5 1
[[0.2883432  0.08414409 0.19524787 0.43226486]]
5 2
[[0.683001   0.00181628 0.00873061 0.3064521 ]]
5 3
[[6.4625138e-01 6.1793573e-04 3.3776341e-03 3.4975305e-01]]
5 4
[[5.7060128e-01 2.7623976e-04 1.6219595e-03 4.2750052e-0

2 4
[[0.4656108  0.00295493 0.00844736 0.52298695]]
2 5
[[0.46916845 0.00125804 0.00427665 0.5252969 ]]
2 6
[[0.47121704 0.00053192 0.00215395 0.52609706]]
2 7
[[4.7295177e-01 2.2198634e-04 1.0753006e-03 5.2575099e-01]]
2 8
[[4.7471040e-01 9.2068505e-05 5.3488964e-04 5.2466261e-01]]
3 1
[[0.56433034 0.02212944 0.05132656 0.36221367]]
3 2
[[0.5562363  0.0071989  0.0192304  0.41733432]]
3 3
[[0.49191597 0.00345953 0.00978731 0.4948372 ]]
3 4
[[0.4657021  0.00162101 0.00524596 0.52743095]]
3 5
[[0.45857555 0.00073125 0.0027855  0.53790766]]
3 6
[[4.5990133e-01 3.1075490e-04 1.4068704e-03 5.3838104e-01]]
3 7
[[4.6128389e-01 1.3189200e-04 7.0952304e-04 5.3787464e-01]]
3 8
[[4.6250150e-01 5.5770332e-05 3.5732196e-04 5.3708541e-01]]
4 1
[[0.5446004  0.02778774 0.06516571 0.36244613]]
4 2
[[0.62718976 0.00384915 0.01290794 0.35605317]]
4 3
[[0.567313   0.00170433 0.00611229 0.4248704 ]]
4 4
[[0.49908733 0.00082299 0.0031438  0.49694592]]
4 5
[[4.6573156e-01 3.8368447e-04 1.6660742e-03 5.322186

2 4
[[0.44228423 0.00786449 0.01883657 0.53101474]]
2 5
[[0.44732943 0.00396986 0.0109907  0.53770995]]
2 6
[[0.44972727 0.00198559 0.00637446 0.5419127 ]]
2 7
[[0.45020285 0.00098213 0.00366311 0.5451519 ]]
2 8
[[4.4970474e-01 4.8791862e-04 2.1146280e-03 5.4769278e-01]]
3 1
[[0.20962404 0.1942863  0.25665107 0.33943856]]
3 2
[[0.52690494 0.01685424 0.03840078 0.41784003]]
3 3
[[0.45631152 0.00951422 0.02220337 0.5119709 ]]
3 4
[[0.43773016 0.0051403  0.01350769 0.54362184]]
3 5
[[0.43413478 0.00261295 0.00792357 0.55532867]]
3 6
[[0.43591338 0.00129972 0.00456359 0.55822325]]
3 7
[[0.43678504 0.00064846 0.00263393 0.5599326 ]]
3 8
[[4.3706134e-01 3.2398451e-04 1.5210995e-03 5.6109363e-01]]
4 1
[[0.1411968  0.27585268 0.28093845 0.30201206]]
4 2
[[0.5912547  0.01280935 0.03565958 0.36027637]]
4 3
[[0.538782   0.00547649 0.01583375 0.4399078 ]]
4 4
[[0.4609326  0.00308662 0.00918578 0.526795  ]]
4 5
[[0.43367437 0.00165668 0.00552108 0.55914783]]
4 6
[[0.42507574 0.00085153 0.00327366 0

2 4
[[0.3429019  0.00544897 0.01294301 0.63870615]]
2 5
[[0.3263471  0.00255355 0.0069756  0.6641237 ]]
2 6
[[0.3081569  0.00118965 0.00374164 0.68691176]]
2 7
[[2.8992584e-01 5.5081578e-04 1.9964545e-03 7.0752698e-01]]
2 8
[[2.7182680e-01 2.5365577e-04 1.0601546e-03 7.2685939e-01]]
3 1
[[0.35008806 0.08717182 0.15898015 0.40375996]]
3 2
[[0.5138509  0.01181085 0.02851461 0.44582364]]
3 3
[[0.4039807  0.0063373  0.0153059  0.57437617]]
3 4
[[0.34145322 0.00323188 0.00861805 0.64669687]]
3 5
[[0.30973497 0.00159613 0.00481885 0.68385005]]
3 6
[[0.29025012 0.00073873 0.0025615  0.7064497 ]]
3 7
[[2.7275926e-01 3.4117227e-04 1.3603036e-03 7.2553927e-01]]
3 8
[[2.5577730e-01 1.5734216e-04 7.2159327e-04 7.4334377e-01]]
4 1
[[0.13485342 0.26130515 0.28617996 0.3176615 ]]
4 2
[[0.59298676 0.00748596 0.02312399 0.37640327]]
4 3
[[0.50931054 0.00333616 0.01036624 0.4769871 ]]
4 4
[[0.3888028  0.00179908 0.00559505 0.60380304]]
4 5
[[0.32004744 0.00090528 0.00309822 0.6759491 ]]
4 6
[[2.8122473e

2 4
[[0.48095092 0.0031337  0.00844719 0.50746816]]
2 5
[[0.4828681  0.00135386 0.00427314 0.5115049 ]]
2 6
[[0.48462793 0.0005854  0.00216221 0.5126245 ]]
2 7
[[4.8624280e-01 2.4833664e-04 1.0791841e-03 5.1242965e-01]]
2 8
[[4.8747587e-01 1.0535612e-04 5.3809641e-04 5.1188070e-01]]
3 1
[[0.4321627  0.05548872 0.11384568 0.3985029 ]]
3 2
[[0.64764804 0.0064388  0.01876684 0.3271463 ]]
3 3
[[0.5873504  0.00301606 0.00911682 0.40051672]]
3 4
[[0.5163172  0.00156461 0.00498924 0.47712898]]
3 5
[[0.48508644 0.00076992 0.00274148 0.5114022 ]]
3 6
[[4.8021612e-01 3.4066330e-04 1.4083131e-03 5.1803488e-01]]
3 7
[[4.7924396e-01 1.4591846e-04 7.0717139e-04 5.1990294e-01]]
3 8
[[4.8012426e-01 6.2688028e-05 3.5576071e-04 5.1945728e-01]]
4 1
[[0.14863376 0.23032881 0.27587962 0.34515783]]
4 2
[[0.688413   0.00393749 0.01421555 0.29343393]]
4 3
[[0.69770706 0.0013905  0.00570763 0.29519483]]
4 4
[[0.6239366  0.00067674 0.00282715 0.37255943]]
4 5
[[5.4526800e-01 3.5401614e-04 1.5414628e-03 4.528365

1 6
[[0.26733556 0.00289874 0.00782547 0.7219403 ]]
1 7
[[0.24464063 0.00143422 0.00441935 0.7495058 ]]
1 8
[[2.2298059e-01 7.0651778e-04 2.4864778e-03 7.7382642e-01]]
2 1
[[0.4639961  0.04513345 0.08675382 0.40411654]]
2 2
[[0.37063265 0.02597965 0.04809044 0.55529726]]
2 3
[[0.31356338 0.01465808 0.02935727 0.64242125]]
2 4
[[0.28982836 0.00745736 0.01687338 0.6858408 ]]
2 5
[[0.26793718 0.0037327  0.00959737 0.7187327 ]]
2 6
[[0.24586816 0.00185154 0.00542237 0.74685794]]
2 7
[[0.22432365 0.00090441 0.00302461 0.77174735]]
2 8
[[2.0371287e-01 4.3675976e-04 1.6712626e-03 7.9417908e-01]]
3 1
[[0.25605467 0.12080917 0.21857622 0.4045599 ]]
3 2
[[0.49410772 0.01388049 0.03403006 0.45798177]]
3 3
[[0.3565074  0.00830328 0.01961655 0.6155728 ]]
3 4
[[0.28249276 0.00456955 0.01157905 0.7013587 ]]
3 5
[[0.24738604 0.00235473 0.00665602 0.7436032 ]]
3 6
[[0.22464713 0.00115433 0.00370776 0.7704907 ]]
3 7
[[2.0428137e-01 5.6687649e-04 2.0705317e-03 7.9308116e-01]]
3 8
[[1.8509617e-01 2.775653

1 6
[[0.3358997  0.00200958 0.00606622 0.65602446]]
1 7
[[0.319382   0.00095101 0.00333151 0.6763355 ]]
1 8
[[3.0264679e-01 4.4937147e-04 1.8240535e-03 6.9507980e-01]]
2 1
[[0.5231581  0.0353397  0.07226531 0.36923698]]
2 2
[[0.431523   0.02029061 0.04066117 0.5075252 ]]
2 3
[[0.36224636 0.01133752 0.02444703 0.6019691 ]]
2 4
[[0.34570438 0.00546061 0.01355311 0.6352819 ]]
2 5
[[0.33043832 0.00261902 0.00748978 0.6594529 ]]
2 6
[[0.3143464  0.00124137 0.00410211 0.6803102 ]]
2 7
[[2.9833910e-01 5.7996355e-04 2.2224486e-03 6.9885850e-01]]
2 8
[[2.8192511e-01 2.6984941e-04 1.2003593e-03 7.1660471e-01]]
3 1
[[0.49419835 0.04306066 0.09559684 0.36714417]]
3 2
[[0.57864475 0.00963932 0.02665416 0.3850618 ]]
3 3
[[0.43934688 0.00580147 0.01534988 0.5395017 ]]
3 4
[[0.34634307 0.00321054 0.00900823 0.6414382 ]]
3 5
[[0.310735   0.00158449 0.00504665 0.6826339 ]]
3 6
[[0.29332593 0.00074651 0.00273866 0.70318884]]
3 7
[[2.7703783e-01 3.5333424e-04 1.4941178e-03 7.2111470e-01]]
3 8
[[2.6139793e

1 6
[[0.20642486 0.00162017 0.00500034 0.78695464]]
1 7
[[1.8029335e-01 7.3271466e-04 2.6288175e-03 8.1634516e-01]]
1 8
[[1.5651800e-01 3.3008363e-04 1.3744875e-03 8.4177750e-01]]
2 1
[[0.49647984 0.0325507  0.07015355 0.40081593]]
2 2
[[0.35727674 0.01913331 0.0391674  0.5844226 ]]
2 3
[[0.26652324 0.00997075 0.02189574 0.70161027]]
2 4
[[0.23446554 0.00460966 0.01164514 0.7492796 ]]
2 5
[[0.20671952 0.00209786 0.00613406 0.78504854]]
2 6
[[0.18034622 0.00094101 0.00319064 0.8155222 ]]
2 7
[[1.5675408e-01 4.1664499e-04 1.6449519e-03 8.4118432e-01]]
2 8
[[1.3544892e-01 1.8444863e-04 8.4550405e-04 8.6352104e-01]]
3 1
[[0.4209698  0.04842994 0.11930983 0.4112905 ]]
3 2
[[0.51273    0.00874608 0.0250369  0.45348707]]
3 3
[[0.3315871  0.00524746 0.0142526  0.6489128 ]]
3 4
[[0.22385278 0.00265631 0.00760306 0.7658878 ]]
3 5
[[0.18153946 0.00122337 0.00397266 0.81326455]]
3 6
[[1.5696187e-01 5.4549769e-04 2.0495318e-03 8.4044302e-01]]
3 7
[[1.3567770e-01 2.4293082e-04 1.0564986e-03 8.630229

这是第2316局游戏，我赢了
最后20盘的胜率为0.7
这是第2317局游戏，我死了
最后20盘的胜率为0.75
这是第2318局游戏，我赢了
最后20盘的胜率为0.7
这是第2319局游戏，我赢了
最后20盘的胜率为0.7
1 1
[[0.3323711  0.06803185 0.09999249 0.49960464]]
1 2
[[0.30859154 0.03708025 0.06095411 0.5933741 ]]
1 3
[[0.28979772 0.01839855 0.03463176 0.65717196]]
1 4
[[0.26460388 0.00886292 0.01911839 0.70741487]]
1 5
[[0.23769899 0.00420903 0.01042186 0.7476702 ]]
1 6
[[0.21083166 0.00198486 0.00563681 0.78154665]]
1 7
[[0.18579677 0.00093325 0.00303405 0.810236  ]]
1 8
[[1.6281396e-01 4.3557523e-04 1.6223397e-03 8.3512813e-01]]
2 1
[[0.45645323 0.03576804 0.07110427 0.4366744 ]]
2 2
[[0.31891713 0.0212089  0.03993203 0.619942  ]]
2 3
[[0.2623097  0.0110387  0.02301934 0.7036322 ]]
2 4
[[0.23390064 0.00525394 0.01249205 0.74835336]]
2 5
[[0.20761886 0.00247139 0.00671415 0.78319556]]
2 6
[[0.18282038 0.00114515 0.00356663 0.8124678 ]]
2 7
[[1.6021085e-01 5.2477629e-04 1.8784659e-03 8.3738589e-01]]
2 8
[[1.3982637e-01 2.4185386e-04 9.9276891e-04 8.5893893e-01]]
3 1
[[0.38618332 0.

这是第2346局游戏，我赢了
最后20盘的胜率为0.75
这是第2347局游戏，我赢了
最后20盘的胜率为0.75
这是第2348局游戏，我死了
最后20盘的胜率为0.75
这是第2349局游戏，我赢了
最后20盘的胜率为0.7
这是第2350局游戏，我赢了
最后20盘的胜率为0.7
这是第2351局游戏，我死了
最后20盘的胜率为0.7
这是第2352局游戏，我赢了
最后20盘的胜率为0.7
这是第2353局游戏，我死了
最后20盘的胜率为0.7
这是第2354局游戏，我死了
最后20盘的胜率为0.65
这是第2355局游戏，我赢了
最后20盘的胜率为0.6
这是第2356局游戏，我赢了
最后20盘的胜率为0.6
这是第2357局游戏，我赢了
最后20盘的胜率为0.6
这是第2358局游戏，我赢了
最后20盘的胜率为0.6
这是第2359局游戏，我赢了
最后20盘的胜率为0.6
1 1
[[0.3720133  0.06886734 0.10063221 0.45848718]]
1 2
[[0.3457998  0.03986163 0.06267765 0.55166095]]
1 3
[[0.34055737 0.02026741 0.0362034  0.6029718 ]]
1 4
[[0.32737434 0.01010399 0.02053755 0.64198416]]
1 5
[[0.3100854  0.00498885 0.01152563 0.67340016]]
1 6
[[0.29079303 0.00245776 0.00644747 0.70030177]]
1 7
[[0.27078402 0.00120288 0.0035848  0.7244283 ]]
1 8
[[2.5135535e-01 5.8920524e-04 1.9928943e-03 7.4606258e-01]]
2 1
[[0.47841626 0.03845106 0.07365268 0.40948004]]
2 2
[[0.39964953 0.02180143 0.04107374 0.5374753 ]]
2 3
[[0.32429934 0.01255729 0.02468782 0.63845557]]
2 4
[[0.30157247 0.0

这是第2380局游戏，我赢了
最后20盘的胜率为0.65
这是第2381局游戏，我赢了
最后20盘的胜率为0.65
这是第2382局游戏，我死了
最后20盘的胜率为0.65
这是第2383局游戏，我赢了
最后20盘的胜率为0.6
这是第2384局游戏，我死了
最后20盘的胜率为0.6
这是第2385局游戏，我赢了
最后20盘的胜率为0.55
这是第2386局游戏，我赢了
最后20盘的胜率为0.6
这是第2387局游戏，我赢了
最后20盘的胜率为0.6
这是第2388局游戏，我赢了
最后20盘的胜率为0.65
这是第2389局游戏，我赢了
最后20盘的胜率为0.7
这是第2390局游戏，我死了
最后20盘的胜率为0.7
这是第2391局游戏，我赢了
最后20盘的胜率为0.7
这是第2392局游戏，我死了
最后20盘的胜率为0.75
这是第2393局游戏，我赢了
最后20盘的胜率为0.7
这是第2394局游戏，我赢了
最后20盘的胜率为0.7
这是第2395局游戏，我赢了
最后20盘的胜率为0.75
这是第2396局游戏，我赢了
最后20盘的胜率为0.75
这是第2397局游戏，我赢了
最后20盘的胜率为0.75
这是第2398局游戏，我赢了
最后20盘的胜率为0.75
这是第2399局游戏，我死了
最后20盘的胜率为0.75
1 1
[[0.37298748 0.06531925 0.0985252  0.463168  ]]
1 2
[[0.34937865 0.03666507 0.06067327 0.5532831 ]]
1 3
[[0.34476545 0.01830606 0.03481176 0.6021167 ]]
1 4
[[0.3323034  0.00895257 0.0195804  0.6391637 ]]
1 5
[[0.31565136 0.00432697 0.01088442 0.66913724]]
1 6
[[0.29669353 0.00208748 0.00603862 0.69518036]]
1 7
[[0.2772888  0.00100216 0.00333282 0.71837616]]
1 8
[[2.5839189e-01 4.7896971e-04 1.8291369e-03 7.3930001e-01]]
2

8 4
[[7.8537393e-01 4.3766740e-05 5.9084315e-04 2.1399151e-01]]
8 5
[[7.6365101e-01 1.8107969e-05 2.6441642e-04 2.3606645e-01]]
8 6
[[6.8929774e-01 9.2224627e-06 1.3760266e-04 3.1055546e-01]]
8 7
[[5.2264822e-01 5.7097318e-06 7.8700985e-05 4.7726735e-01]]
8 8
[[3.4551203e-01 3.6160397e-06 4.7061785e-05 6.5443724e-01]]
这是第2420局游戏，我死了
最后20盘的胜率为0.95
这是第2421局游戏，我赢了
最后20盘的胜率为0.9
这是第2422局游戏，我赢了
最后20盘的胜率为0.9
这是第2423局游戏，我赢了
最后20盘的胜率为0.9
这是第2424局游戏，我死了
最后20盘的胜率为0.9
这是第2425局游戏，我死了
最后20盘的胜率为0.85
这是第2426局游戏，我赢了
最后20盘的胜率为0.8
这是第2427局游戏，我赢了
最后20盘的胜率为0.8
这是第2428局游戏，我赢了
最后20盘的胜率为0.8
这是第2429局游戏，我赢了
最后20盘的胜率为0.8
这是第2430局游戏，我死了
最后20盘的胜率为0.8
这是第2431局游戏，我赢了
最后20盘的胜率为0.75
这是第2432局游戏，我死了
最后20盘的胜率为0.75
这是第2433局游戏，我赢了
最后20盘的胜率为0.7
这是第2434局游戏，我赢了
最后20盘的胜率为0.7
这是第2435局游戏，我死了
最后20盘的胜率为0.75
这是第2436局游戏，我死了
最后20盘的胜率为0.7
这是第2437局游戏，我死了
最后20盘的胜率为0.65
这是第2438局游戏，我赢了
最后20盘的胜率为0.6
这是第2439局游戏，我赢了
最后20盘的胜率为0.6
1 1
[[0.40146804 0.05417392 0.08865925 0.45569873]]
1 2
[[0.3540367  0.02971376 0.05306524 0.56318426]]
1 3
[[0.34

8 1
[[0.02858641 0.16515042 0.47307235 0.33319083]]
8 2
[[0.05337808 0.06280791 0.54931474 0.3344993 ]]
8 3
[[8.0473351e-01 1.3965824e-04 1.9986976e-03 1.9312817e-01]]
8 4
[[8.2796991e-01 1.9221441e-05 3.7426397e-04 1.7163660e-01]]
8 5
[[8.0985349e-01 7.8656249e-06 1.6866517e-04 1.8997009e-01]]
8 6
[[7.4334645e-01 3.9970619e-06 8.8688706e-05 2.5656092e-01]]
8 7
[[5.5290717e-01 2.7329452e-06 5.5288496e-05 4.4703487e-01]]
8 8
[[3.4053195e-01 1.8358119e-06 3.3799821e-05 6.5943241e-01]]
这是第2460局游戏，我赢了
最后20盘的胜率为0.7
这是第2461局游戏，我赢了
最后20盘的胜率为0.7
这是第2462局游戏，我赢了
最后20盘的胜率为0.7
这是第2463局游戏，我死了
最后20盘的胜率为0.75
这是第2464局游戏，我赢了
最后20盘的胜率为0.7
这是第2465局游戏，我死了
最后20盘的胜率为0.7
这是第2466局游戏，我赢了
最后20盘的胜率为0.7
这是第2467局游戏，我死了
最后20盘的胜率为0.7
这是第2468局游戏，我赢了
最后20盘的胜率为0.65
这是第2469局游戏，我死了
最后20盘的胜率为0.65
这是第2470局游戏，我赢了
最后20盘的胜率为0.65
这是第2471局游戏，我死了
最后20盘的胜率为0.7
这是第2472局游戏，我死了
最后20盘的胜率为0.7
这是第2473局游戏，我赢了
最后20盘的胜率为0.65
这是第2474局游戏，我赢了
最后20盘的胜率为0.65
这是第2475局游戏，我赢了
最后20盘的胜率为0.65
这是第2476局游戏，我赢了
最后20盘的胜率为0.65
这是第2477局游戏，我赢了
最后20盘的胜率为0.7


7 5
[[7.3318166e-01 2.1005924e-05 3.2597614e-04 2.6647139e-01]]
7 6
[[5.0209218e-01 1.5564490e-05 2.1119433e-04 4.9768108e-01]]
7 7
[[2.6934773e-01 1.0755874e-05 1.3281498e-04 7.3050869e-01]]
7 8
[[1.2923791e-01 5.6914469e-06 6.8563924e-05 8.7068772e-01]]
8 1
[[0.01858932 0.14864098 0.52588403 0.3068857 ]]
8 2
[[0.02157438 0.0758459  0.6361242  0.26645553]]
8 3
[[7.3503894e-01 3.9255887e-04 6.9550276e-03 2.5761348e-01]]
8 4
[[8.4950441e-01 1.7438902e-05 3.9804020e-04 1.5008013e-01]]
8 5
[[8.2952309e-01 7.3476072e-06 1.7495926e-04 1.7029460e-01]]
8 6
[[7.13353097e-01 4.90661341e-06 1.05241495e-04 2.86536723e-01]]
8 7
[[4.7010395e-01 3.7269888e-06 7.0396723e-05 5.2982187e-01]]
8 8
[[2.4561337e-01 2.4943481e-06 4.2972781e-05 7.5434119e-01]]
这是第2500局游戏，我死了
最后20盘的胜率为0.7
这是第2501局游戏，我死了
最后20盘的胜率为0.65
这是第2502局游戏，我赢了
最后20盘的胜率为0.65
这是第2503局游戏，我赢了
最后20盘的胜率为0.65
这是第2504局游戏，我赢了
最后20盘的胜率为0.65
这是第2505局游戏，我赢了
最后20盘的胜率为0.65
这是第2506局游戏，我赢了
最后20盘的胜率为0.7
这是第2507局游戏，我赢了
最后20盘的胜率为0.75
这是第2508局游戏，我赢了
最后20盘的胜

6 8
[[1.3672629e-01 9.3593862e-06 9.6413249e-05 8.6316794e-01]]
7 1
[[0.02434046 0.14652233 0.5327487  0.2963885 ]]
7 2
[[0.15830883 0.02483815 0.36274183 0.45411125]]
7 3
[[8.992511e-01 4.980136e-05 9.399543e-04 9.975906e-02]]
7 4
[[9.1376048e-01 1.0934084e-05 2.5520026e-04 8.5973397e-02]]
7 5
[[8.7278873e-01 6.7436308e-06 1.4929396e-04 1.2705520e-01]]
7 6
[[6.95709527e-01 6.73377690e-06 1.18400036e-04 3.04165393e-01]]
7 7
[[4.2542145e-01 6.2464469e-06 9.1757262e-05 5.7448059e-01]]
7 8
[[2.1299368e-01 4.0355812e-06 5.4378084e-05 7.8694791e-01]]
8 1
[[0.01708905 0.13975722 0.5510498  0.29210395]]
8 2
[[0.02608295 0.04443524 0.6823407  0.24714108]]
8 3
[[8.6711484e-01 8.6885804e-05 2.0166533e-03 1.3078159e-01]]
8 4
[[9.3750572e-01 4.3753735e-06 1.4775233e-04 6.2342152e-02]]
8 5
[[9.3306160e-01 1.8000208e-06 6.4714419e-05 6.6871949e-02]]
8 6
[[8.7386751e-01 1.3834259e-06 4.3783028e-05 1.2608738e-01]]
8 7
[[6.8795633e-01 1.4864020e-06 3.7058697e-05 3.1200513e-01]]
8 8
[[4.1864628e-01 1.35

6 1
[[0.035947   0.2082765  0.42823884 0.32753772]]
6 2
[[0.571494   0.00695848 0.06426258 0.35728493]]
6 3
[[9.2308575e-01 5.5324297e-05 8.1145129e-04 7.6047495e-02]]
6 4
[[9.2927849e-01 1.9552994e-05 3.2613974e-04 7.0375778e-02]]
6 5
[[8.6636871e-01 1.5549316e-05 2.1512203e-04 1.3340054e-01]]
6 6
[[6.9074070e-01 1.7758679e-05 1.9035491e-04 3.0905113e-01]]
6 7
[[4.7319153e-01 1.4989675e-05 1.4169024e-04 5.2665180e-01]]
6 8
[[3.0599740e-01 9.6268204e-06 8.7934735e-05 6.9390500e-01]]
7 1
[[0.02556406 0.20895845 0.43446687 0.33101067]]
7 2
[[0.10657039 0.04591408 0.4559296  0.3915859 ]]
7 3
[[9.2736942e-01 4.3516688e-05 7.8032212e-04 7.1806706e-02]]
7 4
[[9.5182693e-01 6.7683523e-06 1.6463763e-04 4.8001599e-02]]
7 5
[[9.4773382e-01 3.2145397e-06 8.0680409e-05 5.2182321e-02]]
7 6
[[8.8129729e-01 3.0196450e-06 5.9778511e-05 1.1863992e-01]]
7 7
[[7.203645e-01 3.517859e-06 5.448944e-05 2.795775e-01]]
7 8
[[5.0568354e-01 3.0874410e-06 4.1896252e-05 4.9427149e-01]]
8 1
[[0.01805815 0.20685114 

5 4
[[6.6976076e-01 1.1778119e-04 9.3758968e-04 3.2918388e-01]]
5 5
[[3.9701676e-01 1.0175270e-04 6.7566941e-04 6.0220581e-01]]
5 6
[[2.1227093e-01 6.1066567e-05 3.8805118e-04 7.8727996e-01]]
5 7
[[1.3332148e-01 2.8493452e-05 1.9707489e-04 8.6645299e-01]]
5 8
[[9.8643407e-02 1.2267671e-05 9.7542179e-05 9.0124673e-01]]
6 1
[[0.03704932 0.17496    0.4380047  0.34998605]]
6 2
[[0.7624211  0.0013071  0.01238437 0.22388749]]
6 3
[[8.84957969e-01 5.33193524e-05 7.85015756e-04 1.14203684e-01]]
6 4
[[8.4388959e-01 2.7897268e-05 3.9261204e-04 1.5568990e-01]]
6 5
[[6.5614480e-01 2.4486884e-05 2.7251017e-04 3.4355822e-01]]
6 6
[[3.8294297e-01 2.1044834e-05 1.9746737e-04 6.1683851e-01]]
6 7
[[1.9698107e-01 1.2677425e-05 1.1220158e-04 8.0289406e-01]]
6 8
[[1.13886766e-01 5.94424000e-06 5.60266853e-05 8.86051357e-01]]
7 1
[[0.02648183 0.1835632  0.4326511  0.3573039 ]]
7 2
[[0.33434045 0.01303094 0.15794319 0.49468547]]
7 3
[[9.1055322e-01 2.8352393e-05 5.5460812e-04 8.8863842e-02]]
7 4
[[9.0822965e

4 6
[[2.3109531e-01 4.0256526e-04 1.5419334e-03 7.6696014e-01]]
4 7
[[2.1455574e-01 2.0079843e-04 8.6997566e-04 7.8437352e-01]]
4 8
[[2.02386439e-01 1.00624864e-04 4.92718362e-04 7.97020197e-01]]
5 1
[[0.05852187 0.2560922  0.3143686  0.3710173 ]]
5 2
[[0.7212287  0.00299663 0.01611871 0.25965595]]
5 3
[[7.9416388e-01 4.4458092e-04 3.1057079e-03 2.0228581e-01]]
5 4
[[6.3766479e-01 3.3939077e-04 1.9562726e-03 3.6003956e-01]]
5 5
[[3.9937061e-01 3.0149924e-04 1.4110859e-03 5.9891683e-01]]
5 6
[[2.4748223e-01 2.0157396e-04 8.8586926e-04 7.5143039e-01]]
5 7
[[2.0008536e-01 1.0618310e-04 5.1749754e-04 7.9929096e-01]]
5 8
[[1.7772295e-01 5.2469575e-05 2.9081778e-04 8.2193381e-01]]
6 1
[[0.04236605 0.26586583 0.3101203  0.3816478 ]]
6 2
[[0.2418986  0.0397993  0.19475667 0.5235455 ]]
6 3
[[8.4151268e-01 2.1727258e-04 2.0952520e-03 1.5617481e-01]]
6 4
[[8.1171715e-01 9.9734221e-05 9.4840355e-04 1.8723467e-01]]
6 5
[[6.2194782e-01 8.5911088e-05 6.5015513e-04 3.7731612e-01]]
6 6
[[3.8568583e-01 

4 6
[[0.20579308 0.0011741  0.00339146 0.78964126]]
4 7
[[1.8782264e-01 6.4798846e-04 2.0615556e-03 8.0946779e-01]]
4 8
[[1.7486960e-01 3.6326755e-04 1.2676520e-03 8.2349950e-01]]
5 1
[[0.04369813 0.2694518  0.264572   0.42227808]]
5 2
[[0.0575198  0.1925053  0.32263276 0.42734212]]
5 3
[[0.6597311  0.00230243 0.01148501 0.32648146]]
5 4
[[0.5623053  0.00121922 0.00525918 0.43121627]]
5 5
[[0.32422206 0.00106758 0.003596   0.6711144 ]]
5 6
[[2.1280646e-01 7.3833694e-04 2.3330941e-03 7.8412211e-01]]
5 7
[[1.7264511e-01 3.8192724e-04 1.3355855e-03 8.2563740e-01]]
5 8
[[1.5244411e-01 2.0494591e-04 7.9034531e-04 8.4656060e-01]]
6 1
[[0.02983228 0.27063578 0.2544255  0.44510636]]
6 2
[[0.03548725 0.23532216 0.28726825 0.4419223 ]]
6 3
[[0.3804017  0.01141981 0.06242197 0.5457565 ]]
6 4
[[7.1098745e-01 5.0685054e-04 3.4501059e-03 2.8505564e-01]]
6 5
[[5.3461105e-01 3.9359604e-04 2.0936129e-03 4.6290168e-01]]
6 6
[[3.004017e-01 3.419149e-04 1.435533e-03 6.978209e-01]]
6 7
[[1.8789366e-01 2.39

4 6
[[1.3782457e-01 2.7397613e-04 9.9356496e-04 8.6090797e-01]]
4 7
[[1.19616896e-01 1.27969703e-04 5.23242168e-04 8.79731894e-01]]
4 8
[[1.05588764e-01 6.03487424e-05 2.75705650e-04 8.94075096e-01]]
5 1
[[0.0836549  0.20791563 0.33542898 0.3730005 ]]
5 2
[[0.6921233  0.00226331 0.01016207 0.29545128]]
5 3
[[0.5651395  0.00091775 0.00394035 0.4300024 ]]
5 4
[[3.0816171e-01 6.1016018e-04 2.0790296e-03 6.8914908e-01]]
5 5
[[1.7729084e-01 3.4534154e-04 1.1678956e-03 8.2119590e-01]]
5 6
[[1.3440168e-01 1.5696100e-04 6.1763526e-04 8.6482370e-01]]
5 7
[[1.0424709e-01 6.6610766e-05 3.0308997e-04 8.9538312e-01]]
5 8
[[8.7781891e-02 3.0384801e-05 1.5710668e-04 9.1203064e-01]]
6 1
[[0.06459304 0.214037   0.33264238 0.3887276 ]]
6 2
[[0.682015   0.00338092 0.01583178 0.29877234]]
6 3
[[6.8283284e-01 4.1032568e-04 2.4416281e-03 3.1431517e-01]]
6 4
[[4.8804826e-01 2.5260943e-04 1.2774562e-03 5.1042163e-01]]
6 5
[[2.4350083e-01 1.6240199e-04 6.6860626e-04 7.5566816e-01]]
6 6
[[1.4105976e-01 8.650124

SystemExit: 

d:\miniconda3\lib\site-packages\IPython\core\interactiveshell.py:3561: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
